### PR TITLE
Add support of the wider face dataset

### PR DESCRIPTION
**Pull request by sovrasov**
This PR contains:
- reader of the WIDER Face in the VOC format
- README with instructions how to prepare directory structure
- sample of a training config

### CODE REVIEW

**Comment by vadik6666** [comment]
@sovrasov how to get val.txt and train.txt ? How they should look like?
By default I this [repo](https://github.com/sovrasov/wider-face-pascal-voc-annotations.git) did not create these annotation files.
```
mmdetection
├── mmdet
├── tools
├── configs
├── data
│   ├── WIDER
│   │   ├── WIDER_train
│   |   │   ├── Annotations
│   │   ├── WIDER_val
│   |   │   ├── Annotations
│   │   ├── val.txt
│   │   ├── train.txt

```

**Comment by sovrasov** [comment]
@vadik6666 thanks for catch! I've forgot to merge them. See PR https://github.com/sovrasov/wider-face-pascal-voc-annotations/pull/2/files

**Comment by vadik6666** [comment]
@sovrasov I made the same annotation files and I get 
> FileNotFoundError: img file does not exist: data/WIDER/WIDER_train/57--Angler/57_Angler_peoplefishing_57_861.jpg

**Comment by vadik6666** [comment]
May be we should have this structure:
```
mmdetection
├── mmdet
├── tools
├── configs
├── data
│   ├── WIDER
│   │   ├── WIDER_train
│   |   │   ├── Annotations
│   |   │   ├── images
│   │   ├── WIDER_val
│   |   │   ├── Annotations
│   |   │   ├── images
│   │   ├── val.txt
│   │   ├── train.txt

```
and in config file change line
img_prefix=[data_root + 'WIDER_train/'],
to
img_prefix=[data_root + 'WIDER_train/images'],
?

**Comment by vadik6666** [comment]
Maybe in [dataset/wider.py](https://github.com/sovrasov/mmdetection/blob/wider/mmdet/datasets/wider.py#L33) we should change
`img_infos.append(
dict(id=img_id, filename=osp.join(folder, filename), width=width, height=height))`
to
`img_infos.append(
dict(id=img_id, filename=root.find('path').text, width=width, height=height))`
?

**Comment by sovrasov** [comment]
Current scripts should work correctly. Do you have all the folders like `0--Parade` right inside the  `WIDER_train` folder?

**Comment by vadik6666** [comment]
Aaa, I see your last modification of readme. Yes it will work now. But I didn't have `0--Parade` inside `WIDER_train`. Thats why I changed `filename=osp.join(folder, filename)` to `filename=root.find('path').text` and it works for me.

**Comment by BlueBlueFF** [comment]
@sovrasov Thank you for your code! And I implemented the experiments about wider-face(backbone:resnet 18, head:fcos), but the result seems not very well. The precision and recall are very low(especially for recall). Do you have implemented some training about wider-face and meet this problem?

**Comment by sovrasov** [comment]
@BlueBlueFF I haven't trained any fcos-based detector yet, so I don't know the optimal training strategy for it. WIDER has huge amount of tiny faces and it can be a problem for the most detectors. 
SSD300 config provided in this PR gives recall 0.434 precision 0.029 and AP 0.347. All measurements are done using tools/test.py and then tools/voc_eval.py

**Comment by BlueBlueFF** [comment]
> @BlueBlueFF I haven't trained any fcos-based detector yet, so I don't know the optimal training strategy for it. WIDER has huge amount of tiny faces and it can be a problem for the most detectors.
> SSD300 config provided in this PR gives recall 0.434 precision 0.029 and AP 0.347. All measurements are done using tools/test.py and then tools/voc_eval.py

Thank you for sharing your result, I will do more expriments on widerface.

**Comment by sovrasov** [comment]
@yhcao6 how is the review process? Do I need to change something?

**Comment by yhcao6** [comment]
> @yhcao6 how is the review process? Do I need to change something?

Sorry to reply to you so late. There are no other suggestions but I am a little wired about following code:
```
 if self.min_size:
     w = bbox[2] - bbox[0]
     h = bbox[3] - bbox[1]
     if w < self.min_size or h < self.min_size:
         ignore = True
```
The logic is that when a box is too small, these boxes will be ignored during training as well as **validation**. Is it a convention in `WIDER` dataset to ignore these small boxes? Otherwise, it may be unusual to ignore boxes by ourselves.

**Comment by sovrasov** [comment]
@yhcao6 these boxes will be ignored in validation only if `min_size` will be directly specified in val config. It can be useful because we don't have implementation of the original WIDER metric, but still can get some additional info about performance in different usecases.
In my SSD300 config small boxes are not ignored in val and test configs. Do you mean the case when somebody performs validation on the train?

**Comment by sovrasov** [comment]
@yhcao6  You can also look at README.md from #673. 
According too measured AP = 0.305 seems like MobilenetV2-based single head detector doesn't work at all, but AP on faces > 30 pix = 0.790, so it works for the target usecase.

**Comment by yhcao6** [comment]
In such case it would be better to add an `assert` to exclude this potential danger.

```
if self.min_size:
    assert not self.test_mode
```

**Comment by sovrasov** [comment]
@yhcao6 done

**Comment by yhcao6** [comment]
There are two other problems:

1. `WIDER` and `WIDER face` are two different datasets. Replacing `wider` with `wider_face` to prevent misunderstanding.

2. The import order in `wider.py` is incorrect, it should be
```
import os.path as osp
import xml.etree.ElementTree as ET

import mmcv

from .xml_style import XMLDataset
```

**Comment by yhcao6** [comment]
Thanks for fixing it! It seems the config file is ignored, could you fix it as well to make it consistent?

**Comment by hellock** [comment]
Thanks! @sovrasov

**Comment by ElegantGod** [comment]
It's unnecessary from widerface annotation to voc annotation!
just create a widerface.py, 
```
import os.path as osp

import mmcv
import numpy as np
import cv2

from .custom import CustomDataset


class WIDERFACEDataset(CustomDataset):
    CLASSES = ('face',)

    def __init__(self, **kwargs):
        self.cat2label = {cat: i + 1 for i, cat in enumerate(self.CLASSES)}
        super(WIDERFACEDataset, self).__init__(**kwargs)

    def load_annotations(self, ann_file):

        img_infos = []
        with open(ann_file, 'r') as file:
            annos = file.readlines()
        self.ann_infos_dict = {}
        count = 0
        while count < len(annos):
            name = str(annos[count]).rstrip()
            filename = name
            filepath = osp.join(self.img_prefix, filename)
            img = cv2.imread(filepath)
            width = img.shape[1]
            height = img.shape[0]
            count += 1
            bboxes = []
            labels = []
            bboxes_ignore = []
            labels_ignore = []
            n_anno = int(annos[count])
            for i in range(n_anno):
                count += 1
                bbox = annos[count].split(' ')[0:4]
                bbox = [int(round(float(x))) for x in bbox]
                x1 = max(0, bbox[0])
                y1 = max(0, bbox[1])
                bbox = [
                    x1,
                    y1,
                    int(min(x1+bbox[2], width)),
                    int(min(y1+bbox[3], height))
                ]
                label = self.cat2label['face']
                bboxes.append(bbox)
                labels.append(label)
            bboxes_ignore = np.zeros((0,4))
            labels_ignore = np.zeros((0, ))
            bboxes = np.array(bboxes, ndmin=2) - 1
            labels = np.array(labels)
            ann = dict(
                bboxes=bboxes.astype(np.float32),
                labels=labels.astype(np.int64),
                bboxes_ignore=bboxes_ignore.astype(np.float32),
                labels_ignore=labels_ignore.astype(np.int64))
            self.ann_infos_dict[name] = ann
            count += 1
            img_infos.append(dict(id=name, filename=filename, width=width, height=height))

        return img_infos

    def get_ann_info(self, idx):
        img_id = self.img_infos[idx]['id']
        return self.ann_infos_dict[img_id]
```

**Pull request merged**
