### PR TITLE
Fix test errors

### PR DESCRIPTION
**Pull request by korabelnikov**
see 
https://github.com/open-mmlab/mmdetection/issues/1600

### CODE REVIEW

**Comment by Erotemic** [comment]
I believe I fixed at least part of this (the isinstance part) in #1517.  I'm not sure if the other changes are addressed in my PR.

**Comment by korabelnikov** [comment]
> I believe I fixed at least part of this (the isinstance part) in #1517. I'm not sure if the other changes are addressed in my PR.

Yes, I suppose, you met similar errors. Can you look my PR, please?

**Comment by korabelnikov** [comment]
I can't realize why build failed when no error and tests passed

https://travis-ci.com/open-mmlab/mmdetection/jobs/250997379#L6357

**Comment by Erotemic** [comment]
Your tests failed because of linter checks. See:

```
$ flake8 .
./tools/test.py:34:9: F841 local variable 'e' is assigned to but never used
The command "flake8 ." exited with 1.
```

to fix these errors run: 

```bash
yapf -r -i --style .style.yapf mmdet/ tools/ tests/
isort --apply -rc mmdet/ tools/ tests/
```

**Comment by korabelnikov** [comment]
Thanks

**Comment by Erotemic** [comment]
@korabelnikov FYI, the change that fixed your issue in PR #1517 was reverted due to a misunderstanding I had about the API. You should probably check the discussion there to see if it is relevant to this PR.

**Comment by korabelnikov** [comment]
@Erotemic I'm sorry, but I haven't understand what's wrong

**Comment by hellock** [comment]
Hi @korabelnikov, you may refer to https://github.com/open-mmlab/mmdetection/pull/1517#issuecomment-551203752 and the following discussions. The api of `forward` may be misleading.

**Comment by korabelnikov** [comment]
Hi @hellock !
Thanks, I read that discussion.
I sure it doesn't affect this PR.
Some callers use `test` with image as sole tensor instead of the list.
we can:
-merge this
-correct all callers to enforce call `test([img], ...)` instead of just `test(img, ...)`

what you prefer?

**Comment by hellock** [comment]
Thanks for all your efforts.
Allowing the usage of a sole tensor in `forward_test()` is unexpected and we have fixed the docstring to have a clear definition about the api. The preprocessing in [`inference_detector`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L81-L83) provides an example how to feed the input image. Is there any other cases in your side that requires other behaviors?

BTW, I am curious about the error in #1600, did you modify the testing scripts and it raised such an error? Or there is some bug in the codebase itself?

**Comment by korabelnikov** [comment]
okay. I've understand.

I'll take a look

**Comment by korabelnikov** [comment]
I thought that's a cause not in my changes but all can be.

https://github.com/open-mmlab/mmdetection/blob/4d84161f142b7500089b0db001962bbc07aa869d/mmdet/models/detectors/base.py#L87

I close this PR for a time until some user user meet it.

**Pull request closed without merging**
