### PR TITLE
Add dynamic loss scale support (from apex)

### PR DESCRIPTION
**Pull request by halostorm**

### CODE REVIEW

**Comment by yhcao6** [comment]
It may be better to support both the constant loss scaling and dynamic loss scaling. Since the dynamic loss scaling will introduce extra computation cost and the constant loss scaling can apply to most cases.

**Comment by halostorm** [comment]
@yhcao6  good suggestion! I have update it. pass (loss_scale='dynamic') will activate dynamic loss scale

**Comment by yhcao6** [comment]
There are some duplicate codes that are not used, for example, the `scale_gradient` and `backward` methods which the original `FP16OptimizerHook` has already implemented.
It may be better to merge the class `LossScalar` and `DynamicLossScalar` and rename it as `LossScalar` but add a param `policy` to specify whether we use `dynamic` or `static`.
Please add a docstring to every method and class.

**Comment by yhcao6** [comment]
Hi, @halostorm,
I just reformat some doc and codes, please check that. 
May I ask if you have verified the code by training a model with dynamic loss scaling?
Would you like to add some unit tests for the newly added `LossScaler`? You can add them in tests/test_fp16.py

**Comment by yhcao6** [comment]
Duplicate with https://github.com/open-mmlab/mmcv/pull/585

**Pull request closed without merging**
