### PR TITLE
Fix type error with albumentation

### LINKED ISSUE #2789: Type error with albumentations
**Describe the bug**
When using albumentations, there's a type conflict problem related with this issue in albumentations repo:
https://github.com/albumentations-team/albumentations/issues/614

**Reproduction**
1. What command or script did you run?
I found this error running `python tools/train.py ...` with a pipeline that uses albumentation transforms. I attached a test that reporduces this error.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, following advice given in https://github.com/albumentations-team/albumentations/issues/614.

3. What dataset did you use?
COCO dataset 

**Environment**
1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

```
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GPU 0: TITAN RTX
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX TITAN X
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.5
    - Built with CuDNN 7.6.4
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/opt/conda/conda-bld/pytorch_1574381331675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574381331675/work=/usr/local/src/conda/pytorch-1.3.1 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574381331675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.2.0
MMCV: 0.5.5
MMDetection: 2.0.0+f745a64
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1
```

**Error traceback**
If applicable, paste the error trackback here.
```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/mmdet/datasets/custom.py", line 140, in __getitem__
    data = self.prepare_train_img(idx)
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/mmdet/datasets/custom.py", line 153, in prepare_train_img
    return self.pipeline(results)
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/mmdet/datasets/pipelines/transforms.py", line 331, in __call__
    self.to_rgb)
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/mmcv/image/photometric.py", line 18, in imnormalize
    return imnormalize_(img, mean, std, to_rgb)
  File "/opt/miniconda3/envs/mlflow-461c1a5b7584f9bc87819bca0b77f1bbed5c1045/lib/python3.6/site-packages/mmcv/image/photometric.py", line 38, in imnormalize_
    cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)  # inplace
TypeError: Expected Ptr<cv::UMat> for argument 'dst'
```

### PR DESCRIPTION
**Pull request by mmeendez8**
Fix #2789

### CODE REVIEW

**Comment by xvjiarui** [comment]
Hi @mmeendez8 
Thanks for your report. It seems that normalize of uint8 image is inplace .....

**Comment by mmeendez8** [comment]
Hi @xvjiarui 
Should I change the inplace operation instead? That's the quick fix we did for training when I first got this error.

**Comment by xvjiarui** [comment]
Hi @mmeendez8 
Yes. Your contribution will be truly appreciated. You may open a PR to add `.copy` in mmcv `imnormalize`.

**Comment by hellock** [comment]
@mmeendez8 You may try if the issue has been fixed with the PR in MMCV.

**Comment by mmeendez8** [comment]
I executed the test and everything works now. Thanks

**Comment by hellock** [comment]
@mmeendez8 If so you may just add the unittests in this PR.

**Comment by mmeendez8** [comment]
@hellock test failed, did this run with the last mmcv changes?

**Comment by hellock** [comment]
The changes have been included in the release of mmcv v0.5.6 yesterday. I have tested it locally and the unittests can pass.

**Comment by hellock** [comment]
There has been a file `tests/test_pipelines/test_transform.py`, you may merge the newly added unit tests with existing ones.

**Comment by mmeendez8** [comment]
@hellock just did that and adapt the test to use PIPELINES as the new added tests

**Pull request merged**
