### PR TITLE
erase wrong code in tools/coco_error_analysis.py

### PR DESCRIPTION
**Pull request by honeybadger78**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

When using that Python script, an error occurred. 

The error is **KeyError: 'supercategory' while using coco_error_analysis.py.**

When running with the modified code, the error is resolved.
I resolved the error we were getting when running that file.
Please briefly describe what modification is made in this PR.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMPreTrain.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by hhaAndroid** [comment]
@honeybadger78 Can you provide examples? Is it possible to delete? I need to consider it.

**Comment by honeybadger78** [comment]
> @honeybadger78 Can you provide examples? Is it possible to delete? I need to consider it.

yes.
how can i prove it?

**Comment by hhaAndroid** [comment]
@honeybadger78 If the user-defined data does not have this field, it will indeed throw an error. However, we should consider the case where this field exists. We cannot simply delete the code.

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @honeybadger78,

We'd like to express our appreciation for your valuable contributions to the mmdetection. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Comment by hhaAndroid** [comment]
@honeybadger78 Hi. Do you have any progress?

**Comment by honeybadger78** [comment]
@hhaAndroid No, Thanks :)

**Pull request closed without merging**
