### PR TITLE
allow to configure out the mask_head of the HTC algorithm

### PR DESCRIPTION
**Pull request by MaximilianOtten**
## Motivation
Originally the HTC algorithm it is intended to be used for Instance Segmentation. Nevertheless it is one of the best SOTA algorithms for Object Detection which is living in the mmdetection framework. The HTC algorithm has an interleaved execution of bbox_heads and mask_heads. For Object Detection only the bbox_heads are needed. The design of the HTC algorithms allows to remove the mask_head while the bbox_head keeps working.

## Modification
To get the above mentioned feature working, only the assert for the mask_head has to be removed. This allows to use config files with no mask_head configured, while still being able to use the bbox_head parts of the algorithm. Also all other configurations will still work. Please advice me if I have missed situations where the assert is really needed and therefore more code has to be changed. 

## Use cases
- Use HTC for Object Detection only
- Train custom HTC Object-Detection part (bbox_head) without the need to provide mask annotation data.

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @MaximilianOtten ,
Thanks for your PR. Could you sign the CLA so that we can merge your PR? It would be better to add a unit test for this functionality, e.g., in this directory https://github.com/open-mmlab/mmdetection/tree/master/tests/test_models/test_roi_heads. Would you like to do that?

**Comment by MaximilianOtten** [comment]
Currently, I'm figuring out who has to sign the CLA in our organization. 
Regarding the unit test: I would much appreciate it if one of you guys can do it, or give me a hint what cases have to be covered.

**Comment by ZwwWayne** [comment]
> Currently, I'm figuring out who has to sign the CLA in our organization.
> Regarding the unit test: I would much appreciate it if one of you guys can do it, or give me a hint what cases have to be covered.

Theoretically, you should sign it as this PR is created by you. For the unit test, we wish the unit test to cover the building and forwarding process of the HTCRoIHead with and without mask head.

**Comment by OpenMMLab-Coodinator** [comment]
Hi @MaximilianOtten ！First of all, we want to express our gratitude for your significant PR in this project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
