### PR TITLE
Check for empty predictions in DetLocalVisualizer._draw_instances

### LINKED ISSUE #8771: ValueError in DetLocalVisualizer when there are no predictions
https://github.com/open-mmlab/mmdetection/blob/c9b47820d637ab341ca3ca869116fc3d91030c74/mmdet/visualization/local_visualizer.py#L200

This line throws a ValueError when there are no predictions, as `areas` is empty.

Easy fix will be to check for empty predictions.

### PR DESCRIPTION
**Pull request by levan92**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fixes #8771, where ValueError throws when there are no predictions

### CODE REVIEW

**Review by Czm369 — APPROVED** [review]
LGTM

**Comment by ZwwWayne** [comment]
Hi @levan92 ,
Thanks for your kind contribution. Would you like to fix the lint issue so that we could merge this PR?
The details can be found by clicking the item of lint check as shown below
image

**Review by Czm369 — APPROVED** [review]
LGTM

**Comment by ZwwWayne** [comment]
continued in https://github.com/open-mmlab/mmdetection/pull/8830

**Comment by OpenMMLab-Assistant005** [comment]
Hi @levan92 ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
