### PR TITLE
Fix DyDCNv2 RuntimeError

### PR DESCRIPTION
**Pull request by BubblyYi**
the parameter of offset is not set as continuous will trigger the runtime error: offset must be continuous

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by jbwang1997** [comment]
Hello @BubblyYi, thanks for your contributions. Could you provide the error report before this modification?

**Comment by BubblyYi** [comment]
> Hello @BubblyYi, thanks for your contributions. Could you provide the error report before this modification?
As you can see, this bug can be reproduced in torch==1.3.0, mmcv==1.3.9,
WXWorkCapture_16595835706370

**Review by BIGWangYuDong — APPROVED** [review]
LGTM

**Comment by BIGWangYuDong** [comment]
This PR is to fix errors in lower version PyTorch, which will not affect high version PyTorch

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
