### PR TITLE
Fix device of the tensors in set_nms

### PR DESCRIPTION
**Pull request by max-unfinity**
## Motivation

Fixed `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)` when running CrowdDet model on cuda device (the model uses MultiInstanceBBoxHead roi_head)

## Modification

Just added `tensor.to(device)` to fix the issue in `set_nms` method.
```
        keep = keep.to(bboxes.device)
        ruler = ruler.to(bboxes.device)
```

versions:
- torch==2.0.1
- mmdet==3.0.0
- mmengine==0.7.4

### CODE REVIEW

**Comment by hhaAndroid** [comment]
@max-unfinity Hi. please fix the lint

**Comment by max-unfinity** [comment]
@hhaAndroid HI!
I've fixed the lint. But now it is failed on unittest:
`ImportError: class `CocoPanopticDataset` in mmdet/datasets/coco_panoptic.py: Please install petrel_client to enable PetrelBackend`
I don't know how to fix this

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @max-unfinity,

We'd like to express our appreciation for your valuable contributions to the mmdetection. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Review by hhaAndroid — APPROVED** [review]

**Comment by gitac10** [comment]
> @hhaAndroid HI! I've fixed the lint. But now it is failed on unittest: `ImportError: class "CocoPanopticDataset" in mmdet/datasets/coco_panoptic.py: Please install petrel_client to enable PetrelBackend` I don't know how to fix this

hi,have solved the problem? could you tell me how to do? thank you

**Pull request merged**
