### PR TITLE
Fix typo in README.md of Strong Baselines

### PR DESCRIPTION
**Pull request by Keiku**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix typo in README.md of Strong Baselines.

## Modification

Fixed large-scale "jittor" to large-scale jitter.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by BIGWangYuDong — APPROVED** [review]
LGTM

**Comment by BIGWangYuDong** [comment]
@Keiku Please sign the CLA.

**Comment by Keiku** [comment]
@BIGWangYuDong Sorry I'm late. I think I was able to do CLA.

**Comment by BIGWangYuDong** [comment]
> @BIGWangYuDong Sorry I'm late. I think I was able to do CLA.

Thanks!

**Pull request merged**
