### PR TITLE
[WIP] Support YOLOX inference

### PR DESCRIPTION
**Pull request by shinya7y**
## Motivation

This PR aims to support YOLOX inference. https://arxiv.org/abs/2107.08430

I'm not related to the work but Submitted on behalf of a third-party: Megvii
The original code https://github.com/Megvii-BaseDetection/YOLOX is under Apache-2.0 License.

### Benchmark

| model   | code           | AP AP50 AP75 APS APM APL            |V100 fp32| T4 fp32 |
|:-------:|:--------------:|:-----------------------------------:|:-------:|:-------:|
| YOLOX-s | official       | 0.392 0.587 0.423 0.220 0.443 0.525 | 19.8 ms | 18.5 ms |
| YOLOX-s | ours (9fc82ac) | 0.392 0.587 0.423 0.219 0.444 0.524 | 17.9 ms | 16.1 ms |
| YOLOX-x | official       | 0.505 0.690 0.549 0.332 0.561 0.667 | 30.0 ms | 77.0 ms |
| YOLOX-x | ours (9fc82ac) | 0.505 0.690 0.549 0.332 0.561 0.667 | 29.2 ms | 78.0 ms |

## Modification

- [x] Add YOLOX files mainly to `mmdet/models`
- [x] Debug
- [ ] Refactor
- [ ] Add unit tests
- [ ] Add docstring

## BC-breaking

None

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @shinya7y ,
Thanks for the kind contribution. As we find that more contributors also would like to join the support of YOLOX in MMDetection, we opened a discussion here https://github.com/open-mmlab/mmdetection/discussions/5659 and invite you to join. Hopefully, we could form a collaboration about this exciting feature. Thanks!

**Comment by RangiLyu** [comment]
Hi, we opened a github-project to manage this project. https://github.com/open-mmlab/mmdetection/projects/2
I split this project into multiple sub-projects so that communities and developers can work together.

**Comment by shinya7y** [comment]
> do you plan to support the training?

I cannot support the training because I don't have resources to reproduce the training. I will be able to refactor and review code for training if needed.

**Comment by RangiLyu** [comment]
> > do you plan to support the training?
> 
> I cannot support the training because I don't have resources to reproduce the training. I will be able to refactor and review code for training if needed.

@hhaAndroid and I and other contributors will handle the augmentation and training part. We will open another PR to align training accuracy. You can focus on your refactoring, and after that, we can merge these PRs.

**Comment by shinya7y** [comment]
The missing piece is batchnorm. Great! @hhaAndroid
For YOLOX-x, `score_thr=0.001` (AP 0.505) is much more accurate than `score_thr=0.01` (AP 0.501) with a little extra time.

**Comment by shinya7y** [comment]
The difference of padding does not matter for AP.
`dict(type='Pad', size=(640, 640), pad_val=114.0),` before `Normalize`: `0.392 0.587 0.423 0.219 0.443 0.524`
`dict(type='Pad', size=(640, 640)),` after `Normalize`: `0.392 0.587 0.423 0.219 0.444 0.524`
`dict(type='Pad', size_divisor=32),` after `Normalize`: `0.392 0.587 0.424 0.219 0.443 0.525`

`size=(640, 640)` inference is slower even with `cudnn_benchmark = True` but appropriate for speed benchmark with the official repo.
Zero padding after `Normalize` is natural.

**Pull request closed without merging**
