### PR TITLE
Uint8 fix

### PR DESCRIPTION
**Pull request by ZwwWayne**
Fix https://github.com/open-mmlab/mmdetection/issues/2017
In PyTorch 1.4, using tensor of type `torch.uint8` will cause a massive warning.
To avoid that, the `inside_flags` is converted to `bool` type. However, ***`Tensor.bool()` is not supported in the PyTorch 1.1, the `and` operation is also invalid for bool tensor, as well as `.any()`***.
Therefore, we use `tensor.type(torch.bool)` here.
The modification has been tested with two environments: PyTorch 1.1 & PyTorch 1.4.

### CODE REVIEW

**Comment by wduo** [comment]
In PYTORCH="1.3" ARG CUDA="10.1" ARG CUDNN="7", there are still massive warnings here.
How can I fix it?

**Comment by wduo** [comment]
@ZwwWayne

**Comment by ZwwWayne** [comment]
In PYTORCH="1.4" there is no warning, I will also try your environments to see what happened.

**Comment by iamRyanChia** [comment]
In pytorch 1.4, training with config "cascade_rcnn_r101_fpn_1x.py" still exist this warnings.

**Comment by EvenStrangest** [comment]
The below task also produces this error.

```
root@1bac3eaaf785:/mmdetection# python tools/train.py configs/htc/htc_x101_64x4d_fpn_20e_16gpu.py
2020-03-10 14:49:23,916 - mmdet - INFO - Environment info:
------------------------------------------------------------
TorchVision: 0.4.1a0+d94043a
OpenCV: 4.2.0
MMCV: 0.3.2
MMDetection: 1.1.0+e08a1ee
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1
```

**Pull request merged**
