### PR TITLE
Update cross_entropy_loss.py

### PR DESCRIPTION
**Pull request by ggjy**
Fix bug: device type when copying weight value.

### CODE REVIEW

**Review by hellock — APPROVED** [review]

**Comment by hellock** [comment]
Could you fix the linting error?

**Comment by ggjy** [comment]
> Could you fix the linting error?

Hi, it seems that it's a problem from mmdetection's latest commit. Please refer to [this link.](https://github.com/open-mmlab/mmdetection/actions/runs/391873935)

**Comment by hellock** [comment]
The linting error is `W291 trailing whitespace`, caused by the newly updated codes. Please refer to https://github.com/open-mmlab/mmdetection/pull/4224/checks?check_run_id=1490397887 for details.

**Comment by ggjy** [comment]
Thanks for pointing out that, I have fixed the error.

**Comment by OpenMMLab-Assistant-007** [comment]
Hi!
@ggjy 
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
