### PR TITLE
Parameters of DilatedEncoder

### PR DESCRIPTION
**Pull request by Shanyaliux**
Add the original fixed parameter block_dilations as an incoming parameter

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

When I used yolof, I modified the modification and found that the parameter named block_dilations of DilatedEncoder is fixed. If I have num_residual_blocks as other values, this parameter cannot be very convenient.

## Modification

I modified this parameter of DilatedEncoder to be an incoming parameter and added a default value in its config file.
- DilatedEncoder modifies the position 
[https://github.com/Shanyaliux/mmdetection/blob/aa99c91d64f4de35ef8040493d0cf5453d662476/mmdet/models/necks/dilated_encoder.py#L68](https://github.com/Shanyaliux/mmdetection/blob/aa99c91d64f4de35ef8040493d0cf5453d662476/mmdet/models/necks/dilated_encoder.py#L68)
[https://github.com/Shanyaliux/mmdetection/blob/aa99c91d64f4de35ef8040493d0cf5453d662476/mmdet/models/necks/dilated_encoder.py#L74](https://github.com/Shanyaliux/mmdetection/blob/aa99c91d64f4de35ef8040493d0cf5453d662476/mmdet/models/necks/dilated_encoder.py#L74)
- yolof configuration file modification location
[https://github.com/Shanyaliux/mmdetection/blob/aa99c91d64f4de35ef8040493d0cf5453d662476/configs/yolof/yolof_r50_c5_8x8_1x_coco.py#L25](https://github.com/Shanyaliux/mmdetection/blob/aa99c91d64f4de35ef8040493d0cf5453d662476/configs/yolof/yolof_r50_c5_8x8_1x_coco.py#L25)

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by hhaAndroid — APPROVED** [review]

**Comment by Shanyaliux** [comment]
In the test process after the first submission, I noticed that the error was reported because the new block_dilations was missing when its test function called DilatedEncoder.
The error message is as follows:
```
    def test_dilated_encoder():
        in_channels = 16
        out_channels = 32
        out_shape = 34
>       dilated_encoder = DilatedEncoder(in_channels, out_channels, 16, 2)
E       TypeError: __init__() missing 1 required positional argument: 'block_dilations'
```
So I fixed the bug in the latest commit

**Comment by Shanyaliux** [comment]
I noticed that you released v2.24.0, do I need to resubmit on the new version?

**Review by ZwwWayne — APPROVED** [review]

**Comment by Shanyaliux** [comment]
Sorry, I don't know how to solve this error, it shouldn't be my problem.

**Comment by ZwwWayne** [comment]
> Sorry, I don't know how to solve this error, it shouldn't be my problem.  

Do not worry, it is caused by other issues and have been fixed in dev branch.

**Comment by ZwwWayne** [comment]
> Sorry, I don't know how to solve this error, it shouldn't be my problem.  

Do not worry, it is caused by other issues and have been fixed in dev branch.

**Pull request merged**
