### PR TITLE
Change qq group qrcode to Group3

### PR DESCRIPTION
**Pull request by STLAND-admin**
## Motivation

QQ group qrcode needs to be updated

## Modification

qq_group_qrcode is changed from Group2 to Group3

### CODE REVIEW

**Comment by RangiLyu** [comment]
Please use the image link instead of adding the image directly to the repository.

**Review by RangiLyu — CHANGES_REQUESTED** [review]
Should not commit images into the repo.
Please replace the image with a link like this:
```
![qq_group_qrcode](https://user-images.githubusercontent.com/12907710/179137838-2acaee56-3887-4347-93b8-1adb5e43b768.jpg)
```

qq_group_qrcode

**Comment by STLAND-admin** [comment]
@RangiLyu I am not sure if you mean replacing the .jpg file with a markdown file that contain the link of the image:(

**Comment by vansin** [comment]
qq_group_qrcode

**Pull request closed without merging**
