### PR TITLE
Update formatting.py

### PR DESCRIPTION
**Pull request by captainIT**
## Motivation
PackDetInputs 使用默认构造函数的meta_keys，但数据增强，没用flip的时候会报错

## Modification

这是[mmsegmentation](https://github.com/open-mmlab/mmsegmentation/tree/main)的处理方式

https://github.com/open-mmlab/mmsegmentation/blob/30a3f94f3e2916e27fa38c67cc3b8c69c1893fe8/mmseg/datasets/transforms/formatting.py#L97C22-L97C22

### CODE REVIEW

**Comment by noreenanwar** [comment]
> ## Motivation
> PackDetInputs 使用默认构造函数的meta_keys，但数据增强，没用flip的时候会报错
> 
> ## Modification
> 这是[mmsegmentation](https://github.com/open-mmlab/mmsegmentation/tree/main)的处理方式
> 
> https://github.com/open-mmlab/mmsegmentation/blob/30a3f94f3e2916e27fa38c67cc3b8c69c1893fe8/mmseg/datasets/transforms/formatting.py#L97C22-L97C22

I got the issue for  'border' like AssertionError: `border` is not found in `results`, the valid keys are ['img_path', 'img_id', 'seg_map_path', 'height', 'width', 'instances', 'sample_idx', 'img', 'img_shape', 'ori_shape', 'scale', 'scale_factor', 'keep_ratio', 'homography_matrix', 'gt_bboxes', 'gt_ignore_flags', 'gt_bboxes_labels'].

**Comment by hhaAndroid** [comment]
> 

May I know which configuration?

**Review by hhaAndroid — APPROVED** [review]

**Comment by hhaAndroid** [comment]
> > > 
> > 
> > 
> > May I know which configuration?
> 
> For me it's centernet_r18-dcnv2_8xb16-crop512-140e_coco.py.

You need include 'border' in PackDetInputs

```python
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'border'))
```

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @captainIT,

We'd like to express our appreciation for your valuable contributions to the mmdetection. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Pull request merged**
