### PR TITLE
Change all fp16 operation to using MMCV

### PR DESCRIPTION
**Pull request by RyanXLi**
Training and inference with config 'configs/fp16/faster_rcnn_r50_fpn_fp16_1x_coco.py' has been tested to have the same mAP.

### CODE REVIEW

**Comment by yhcao6** [comment]
Can you check the formatter of your code editor? It seems this PR introduces many unnecessary changes.

**Comment by RyanXLi** [comment]
@yhcao6 The docformatter problem has been fixed. Thanks.

**Review by yhcao6 — APPROVED** [review]

**Comment by hellock** [comment]
Please check if the fp16 module in mmdet is updated and diverged from mmcv.

**Comment by RyanXLi** [comment]
I have checked and the fp16 in mmdet in current master is identical to mmcv. However, [#1502](https://github.com/open-mmlab/mmdetection/pull/1502) may need to be moved to mmcv.

**Pull request merged**
