### PR TITLE
Random Seed Issue

### PR DESCRIPTION
**Pull request by HarborYuan**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

#6339 

## Modification

#6339 

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by HarborYuan** [comment]
@hhaAndroid @RangiLyu

**Comment by RangiLyu** [comment]
Thanks for your contribution! We are now assessing the impact of this change.
Here are some brief suggestions:

- When the seed is not set in the args, it will randomly generate a seed and broadcast to all ranks. How about integrating these codes into the `set_random_seed` function in `mmdet/apis/train.py`?
- When `args.seed` is `None`, the `seed` in `cfg` will set to `None`. The hyperparam `cfg.seed` is used in some other places such as the data loader sampler. I think the `args.seed` should also be set to the `random_num` in this PR.

**Comment by HarborYuan** [comment]
Thanks for your reponse.

You can make changes on the PR based on your understanding. By the way, I think there is another thing needs to be considered:
The current codes only support gpu, do we need to support multi process cpu tasks?

**Comment by RangiLyu** [comment]
> You can make changes on the PR based on your understanding. 

Okay, we will take over this PR and do some modifications.

> By the way, I think there is another thing needs to be considered: The current codes only support gpu, do we need to 
> support multi process cpu tasks?

CPU DDP or DP training support is not in our plan.

**Comment by hhaAndroid** [comment]
@HarborYuan @RangiLyu I will follow this PR to continue to modify.

**Pull request closed without merging**
