### PR TITLE
Fix type errors in roi_align_v2

### PR DESCRIPTION
**Pull request by c1aris**
This PR fixes the issue mentioned in #2262.

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @c1aris ,
Thanks for your kind contribution.
I have tested this PR in the CentOS system and it also works well. So the RoIAlign should work with both Windows and Linux after merging this PR.

**Comment by c1aris** [comment]
@ZwwWayne That's great! May I ask that do you have any plans to re-benchmark the models using RoIAlignV2?

**Comment by ZwwWayne** [comment]
Yes, the re-benchmarked models with RoIAlignV2 and all the BC-breaking changes will be released in about two weeks.

**Comment by c1aris** [comment]
Glad to hear that. Thank you so much!

**Pull request merged**
