### PR TITLE
add gui

### PR DESCRIPTION
**Pull request by Chien-Hung**
Hello, 

I add a lightweight gui for easily visualizing the detection results. It could display detection results with different threshold dynamically, and would be convenient for verifying detection results and groundtruth.

The GUI looks like this video https://www.youtube.com/watch?v=4imQyECTik0&t=13s, but the command will be 
python tools/DetVisGUI.py ${CONFIG_FILE} ${RESULT_FILE}
example: python tools/DetVisGUI.py configs/cascade_rcnn_r50_caffe_c4_1x.py work_dirs/cascade_rcnn_r50_c4_1x/results.pkl

Hoping this would be useful.

### CODE REVIEW

**Comment by gjxgjxgjxgjx** [comment]
What does the result file refer to? How is it generated?

**Comment by Chien-Hung** [comment]
The result file is .pkl file. It can be generated by the following command.

python tools/test.sh configs/mask_rcnn_r50_fpn_1x_coco.py \
    checkpoints/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth \
    --out results.pkl

**Comment by gjxgjxgjxgjx** [comment]
solved! This tool is great.

**Comment by hellock** [comment]
Thanks for your nice work! To ease the maintenance, I suggest that you may host the gui tool on a new github repo or gist, and add a link to it in the documentation of mmdetection.

**Comment by Chien-Hung** [comment]
This work has been added by a link in the getting_started.md of mmdetection.

**Pull request closed without merging**
