### PR TITLE
[CodeCamp2023-495]Translation into Chinese of an English document.(1)

### PR DESCRIPTION
**Pull request by yeungkong**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

I would like to translate an English document into Chinese.

## Modification

I have done the translation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMPreTrain.
4. The documentation has been modified accordingly, like docstring or example tutorials.

[学习更多与配置相关的事.docx](https://github.com/open-mmlab/mmdetection/files/12158953/default.docx)

### CODE REVIEW

**Comment by BIGWangYuDong** [comment]
The `tutorials` branch should rebase or merge the `main` branch

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @yeungkong,

We'd like to express our appreciation for your valuable contributions to the mmdetection. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Comment by hhaAndroid** [comment]
@yeungkong Thank you very much, but your PR record is incorrect. There shouldn't be 203 files modified in the file changes.

**Comment by yeungkong** [comment]
@hhaAndroid This is weird. I didn't change that files. I just want to upload the docx file which is the Chinese version of the document. How can I fix this?

**Comment by hhaAndroid** [comment]
> @hhaAndroid This is weird. I didn't change that files. I just want to upload the docx file which is the Chinese version of the document. How can I fix this?



> The `tutorials` branch should rebase or merge the `main` branch

The tutorials branch should rebase or merge the dev-3.x branch

**Comment by hhaAndroid** [comment]
@yeungkong If you are not familiar with the process, I suggest closing this pull request and resubmitting it following the correct steps.

**Pull request closed without merging**
