### PR TITLE
[Fix]: Fix get train_pipeline method of val workflow

### PR DESCRIPTION
**Pull request by Lehsuby**
## Motivation

When using a Wrapper Dataset, for example, `RepeatDataset`, an internal dataset with the dataset key is used. If you additionally use several workflows `workflow = [('train', 2), ('val', 1)]`, an error occurs on the line, since this key does not exist.
```
val_dataset.pipeline = cfg.data.train.pipeline

AttributeError: 'ConfigDict' object has no attribute 'pipeline'
```

## Modification

Added name matching check. Also added the ability to get **train_pipeline** from the Wrapper Dataset.
`tools/train.py`

## BC-breaking

No

## Use cases

When using a wrapper Dataset, for example, `RepeatDataset`, an internal dataset with the dataset key is used. If you additionally use several workflows `workflow = [('train', 2), ('val', 1)]`, an error occurs on the line, since this key does not exist.

`configs/_base_/datasets/voc0712.py`
```
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1000, 600), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1000, 600),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/trainval.txt',
                data_root + 'VOC2012/ImageSets/Main/trainval.txt'
            ],
            img_prefix=[data_root + 'VOC2007/', data_root + 'VOC2012/'],
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='mAP')

# Running 2 epochs for training and 1 epoch for validation, iteratively.
workflow = [('train', 2), ('val', 1)]
```

## Checklist

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] The modification is covered by complete unit tests.

### CODE REVIEW

**Review by ZwwWayne — APPROVED** [review]

**Comment by razimgit** [comment]
After these changes if I use validation in my workflow `workflow = [("train", 1), ("val", 1)]` and don't use a wrapper dataset, my training fails to start.

In `tools/train.py` I get `AttributeError: 'ConfigDict' object has no attribute 'dataset'`:
```python
if len(cfg.workflow) == 2:
        assert 'val' in [mode for (mode, _) in cfg.workflow]
        val_dataset = copy.deepcopy(cfg.data.val)
        val_dataset.pipeline = cfg.data.train.get(
            'pipeline', cfg.data.train.dataset.get('pipeline'))
```
in `cfg.data.train.dataset.get('pipeline')` because standard data config doesn't have a `dataset` key.

**Comment by Lehsuby** [comment]
@razimgit Can you share the config or part of it where you have the data announced?

By default, the pipeline dataset is located on the `data.train.pipeline` path, but if we use a shell such as `RepeatDataset`, then the pipeline is located on the `data.train.dataset.pipeline` path. Therefore, there are two checks going on here in order to process both cases. You can see examples of configs here `configs/_base_/datasets/voc0712.py`, `configs/_base_/datasets/coco_instance.py`

**Comment by PushpakBhoge** [comment]
@Lehsuby seems like this line
```python
val_dataset.pipeline = cfg.data.train.get('pipeline', cfg.data.train.dataset.get('pipeline'))
```
is checking this section ` cfg.data.train.dataset.get('pipeline')` in advance

if I run with this it works perfectly for non RepeatDataset dataset
```python
val_dataset.pipeline = cfg.data.train.get('pipeline')
```
but as soon as I run with this, I get the error `AttributeError: 'ConfigDict' object has no attribute 'pipeline'`
```python
val_dataset.pipeline = cfg.data.train.get('pipeline', cfg.data.train.dataset.get('pipeline'))
```

This is surly weird maybe have something to do with Python version ??

**Comment by t19cs008** [comment]
I'm sorry if I misunderstood.
I tried to train coco2017 dataset using "configs/\_base\_/datasets/coco_instance.py", but this error is occured.
```
Traceback (most recent call last):
  File "/mmdetection/tools/train.py", line 248, in <module>
    main()
  File "/mmdetection/tools/train.py", line 225, in main
    print(cfg.data.train.dataset)
  File "/mmcv/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dataset'
```

I think this change is causing the error.
How to fix this error.
using RepeatDataset and time=1?
or fix the previous implementation by myself?

**Pull request merged**
