### PR TITLE
Objects as points

### PR DESCRIPTION
**Pull request by Ridhwanluthra**
This implements [Objects as Points](https://arxiv.org/abs/1904.07850)

Additions:
* centernet detector
* hourglass backbone
* DLA backbone
* centernet head and loss
* Integrate centernet data loading
* configs for voc and coco training and testing
* centernet debugger

### CODE REVIEW

**Comment by Ridhwanluthra** [comment]
Links to fully trained models for [pascal](https://drive.google.com/file/d/1AaNmxuodxeCUGCC-Ld8qlpOC7yjdwQTj/view?usp=sharing) and [coco](https://drive.google.com/file/d/13kMKeEibZvvr671ATWfY4QSlayR6DLTZ/view?usp=sharing)

**Comment by Epiphqny** [comment]
> Links to fully trained models for [pascal](https://drive.google.com/file/d/1AaNmxuodxeCUGCC-Ld8qlpOC7yjdwQTj/view?usp=sharing) and [coco](https://drive.google.com/file/d/13kMKeEibZvvr671ATWfY4QSlayR6DLTZ/view?usp=sharing)

whats the mAP of the trained model, is it DLA or hg?

**Comment by Ridhwanluthra** [comment]
Using DLA, The mAP on pascal is 0.791

**Comment by Epiphqny** [comment]
> Using DLA, The mAP on pascal is 0.791

Thanks. Does it support multi-scale testing?

**Comment by lxtGH** [comment]
> Using DLA, The mAP on pascal is 0.791

what is results on COCO?

**Comment by mrsempress** [comment]
I'm sorry, when I run your code with command `python tools/test.py configs/centernet_dla_1x.py checkpoints/ctdet_coco_dla_1x.pth --out results.pkl`, then I got the error.
> The model and loaded state dict do not match exactly
Traceback (most recent call last):
    File "tools/test.py", line 311, in <module>
        main()
    File "tools/test.py", line 264, in main
        if 'CLASSES' in checkpoint['meta']:
KeyError: 'meta'

So, could you tell me what's wrong?
At first I thought maybe the config and checkpoints file are not matched. But I have tried three combinations: 
1. `python tools/test.py configs/centernet_dla_1x.py checkpoints/ctdet_coco_dla_1x.pth --out results.pkl`
2. `python tools/test.py configs/centernet_dla_2x.py checkpoints/ctdet_coco_dla_1x.pth --out results.pkl`
3. `python tools/test.py configs/centernet_hg.py checkpoints/ctdet_coco_dla_1x.pth --out results.pkl`

And all got the same error messages.
So, waiting for your reply. @Ridhwanluthra

**Comment by chenchongsong** [comment]
> > Using DLA, The mAP on pascal is 0.791
> 
> what are results on COCO?

I've tested the fully trained coco model, achieving a bbox_mAP of 39.0

**Comment by Epiphqny** [comment]
> > > Using DLA, The mAP on pascal is 0.791
> > 
> > 
> > what are results on COCO?
> 
> I've tested the fully trained coco model, achieving a bbox_mAP of 39.0

Ok, thanks for you reply!

**Comment by feixiangdekaka** [comment]
> > > Using DLA, The mAP on pascal is 0.791
> > 
> > 
> > what are results on COCO?
> 
> I've tested the fully trained coco model, achieving a bbox_mAP of 39.0

How to down the code?

**Comment by mathmanu** [comment]
Hi, good work, Thank you. I have one question. 
RetinaNet and FCOS are based on SingleStageDetector. Shouldn't this also be based on SingleStageDetector? Wondering why this is based on TwoStageDetector.

**Comment by 237014845** [comment]
@chenchongsong How many gpus have you used for training? What is the learning rate? How many days have you trained

**Comment by Epiphqny** [comment]
> > > Using DLA, The mAP on pascal is 0.791
> > 
> > 
> > what are results on COCO?
> 
> I've tested the fully trained coco model, achieving a bbox_mAP of 39.0

May I ask the speed(FPS) of inference?

**Comment by ZwwWayne** [comment]
Already supported in #4602

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @Ridhwanluthra ！We are grateful for your efforts in helping improve mmdetection open-source project during your personal time. 

Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）

Thank you again for your contribution❤

**Pull request closed without merging**
