### PR TITLE
Add a lightweight ssd-based face detector

### PR DESCRIPTION
**Pull request by sovrasov**
This PR contains
- Reader for the WIDER face dataset
- Lightweight single head SSD face detector based on the MobileNetV2
- Tools to export SSD into onnx format with ability to deploy the resulting snapshots via [Open VINO](https://software.intel.com/en-us/openvino-toolkit)

cc @snosov1

### CODE REVIEW

**Comment by yhcao6** [comment]
Thanks for the PR. Could you add a "README.md" to show
1. How to prepare the WIDER dataset and the directory structure.
2. The performance of the model and url to download.

**Comment by sovrasov** [comment]
Ok, will do it soon.

**Comment by sovrasov** [comment]
@yhcao6 done

**Comment by sovrasov** [comment]
@yhcao6 what are the future steps to get this merged?

**Comment by hellock** [comment]
Hi @sovrasov, your nice work is much appreciated!

This PR contains too much (and maybe unrelated) changes and new features, which make it hard to be reviewed and merged.

The main parts of this PR are:
1. A new dataset WIDER face.
2. A new backbone MobileNet v2 and the integration of SSD.

We believe 1 will benefit the research and application of face detection and 2 will also be very helpful. I suggest creating 2 independent PRs for these two features and they will be reviewed in higher priority.

Other enhancements are:
3. A tool to export models to ONNX.
4. A tool to compute flops of single stage detectors.
5. A webcam demo.

These tools or demos are also very useful. The concern is that we hope all provided tools work well in general cases and current implementation are too specific. If you would like to improve these features, we can have a further discussion, otherwise if you do not have much time to do that, we can put them to planned (but not urgent) features and our team can help with the implementation later.

**Comment by TTMRonald** [comment]
@sovrasov Hi, can you tell me where to add the code to convert onnx?

**Comment by SnowRipple** [comment]
Does the tool to export to ONNX is for all models or just the SSD?

I struggle to convert any models from this repo to ONNX..

**Comment by sovrasov** [comment]
@SnowRipple  This converter works for SSD only.

**Comment by SnowRipple** [comment]
Thanks @sovrasov! 

I learned a lot from your code for converting SSD to onnx. 
I know it's a little off topic but I am trying to use it for retinanet conversion, and I believe I am close but I am gettting an error (and lots of warnings):

/home/snow_ripple/workspace/01_detection/mmdet/models/necks/fpn.py:106: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  target[:, :, :, :75] = inputs[1]
/home/snow_ripple/workspace/01_detection/mmdet/core/anchor/anchor_generator.py:48: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  xx = x.repeat(len(y))
/home/snow_ripple/workspace/01_detection/mmdet/core/anchor/anchor_generator.py:49: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  yy = y.view(-1, 1).repeat(1, len(x)).view(-1)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:9: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cls_score_list = cls_scores.tolist()
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:10: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bbox_pred_list = bbox_preds.tolist()
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:13: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cls_score = torch.Tensor(cls_score_list[img_id]).detach().to(priors.device)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:14: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  bbox_pred = torch.Tensor(bbox_pred_list[img_id]).detach().to(priors.device)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:32: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_pre > 0 and cls_scores.shape[0] > nms_pre:
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:40: TracerWarning: new_tensor is a legacy constructor and is not supported in the JIT.
  means = deltas.new_tensor(means).repeat(1, deltas.size(1) // 4)
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:41: TracerWarning: new_tensor is a legacy constructor and is not supported in the JIT.
  stds = deltas.new_tensor(stds).repeat(1, deltas.size(1) // 4)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:44: TracerWarning: new_tensor is a legacy constructor and is not supported in the JIT.
  mlvl_bboxes /= mlvl_bboxes.new_tensor(scale_factor)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:44: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator div_. This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  mlvl_bboxes /= mlvl_bboxes.new_tensor(scale_factor)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:46: TracerWarning: new_zeros is a legacy constructor and is not supported in the JIT.
  padding = cls_scores.new_zeros(cls_scores.shape[0], 1)
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:34: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i in range(1, num_classes):
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:36: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not cls_inds.any():
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] == 4:
/home/snow_ripple/workspace/01_detection/mmdet/ops/nms/nms_wrapper.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if dets_th.shape[0] == 0:
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:50: TracerWarning: new_full is a legacy constructor and is not supported in the JIT.
  dtype=torch.long)
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.shape[0] > max_num:
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:148: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  output_for_img[:, 0] = img_id
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:149: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  output_for_img[:, 1] = labels
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:150: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  output_for_img[:, 2] = scores
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:151: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  output_for_img[:, 3:] = coords
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:152: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  output[img_id, 0, :output_for_img.size()[0]] = output_for_img
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:152: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  output[img_id, 0, :output_for_img.size()[0]] = output_for_img
Traceback (most recent call last):
  File "/home/snow_ripple/workspace/01_detection/tools/onnx_export.py", line 44, in <module>
    main()
  File "/home/snow_ripple/workspace/01_detection/tools/onnx_export.py", line 40, in main
    model.module.onnx_export(export_name=args.output, **data)
  File "/home/snow_ripple/workspace/01_detection/mmdet/models/detectors/base.py", line 98, in onnx_export
    torch.onnx.export(self, img, export_name, verbose=False)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

I checked the code in question:

 if desc == 'is':
            for v in value.node().inputs():
                if v.node().kind() != 'onnx::Constant':
                    raise RuntimeError("Failed to export an ONNX attribute, "
                                       "since it's not constant, please try to make "
                                       "things (e.g., kernel size) static if possible")
            return [int(v.node()['value']) for v in value.node().inputs()]

and the node().kind() produces "Floor" instead of "Constant".

Any idea why?

**Pull request closed without merging**
