### PR TITLE
[Docs] Update MMDet_Tutorial.ipynb of 3.x

### PR DESCRIPTION
**Pull request by RangeKing**
## Motivation

Update MMDet_Tutorial.ipynb of 3.x

## Modification

- `demo/MMDet_Tutorial.ipynb`
- `tools/misc/download_dataset.py`

### CODE REVIEW

**Comment by hhaAndroid** [comment]
@RangeKing Please run it again based on the latest 3.0.0 branch. Thank you.

**Comment by RangeKing** [comment]
> @RangeKing Please run it again based on the latest 3.0.0 branch. Thank you.

I've run it again and updated the notebook.

**Comment by hhaAndroid** [comment]
@RangeKing Can you fix the ci please?

**Comment by RangeKing** [comment]
> @RangeKing Can you fix the ci please?

Done.

**Pull request merged**
