### PR TITLE
Initial jit support

### PR DESCRIPTION
**Pull request by DXist**
Started to work on jit support. TorchScript is a limited statically typed subset of Python and requires some adaptations.

Jit can be configured via `jit` config flag on module level. Unjittable code parts can be wrapped in `@torch.jit.ignore`.

This PR contains jit fixes for Resnet backbone.

I've done a benchmark on a K80 GPU for a single image. The Resnet 50 backbone inference time is decreased from ~10-12ms before jitting to ~6ms after jitting.

I'm going to continue incrementally enable jit support for Mask R-CNN architecture.

### CODE REVIEW

**Comment by hellock** [comment]
Thanks for your efforts to add JIT support! Just a reminder that you may need to consider the back compatibility, and keep the original features (such as checkpointing, which is useful for large models).

**Comment by DXist** [comment]
@hellock , checkpointing is done in native Python code - jit-compiled code can call it. I haven't tested it in train pipeline yet.
Nevertheless `jit` option is disabled by default and eager execution mode is default one.

Currently TorchScript doesn't support functions with variadic arguments or keyword only arguments.

For optional layers I had either to mark them as a `constant` or make them nonoptional - like `self.downsample` attribute is either a `nn.Identity` instance or a given downsample module instance.

**Comment by DXist** [comment]
@hellock , I've adapted ResNext for TorchScript as well. And added a couple of doctests with jitting.

**Comment by DXist** [comment]
I've done a series of steps to be TorchScript compatible and maintain backward compatibility. The steps are described below. @hellock , is it an acceptable route to go?

1. First I had to get rid of `getattr` calls and make all module names known during compile time.
Res layers with name prefixes like 'backbone.layer1.' are moved to prefix `backbone.res_layers.0`. TorchScript supports iteration over constant module list ( `self.res_layers` ) and unrolls the loop in compile time.
Normalization layers got fixed names like `backbone.norm1`.
2. To support backward compatibility I've looked through [pytorch load state dict machinery](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L712) and decided to use [load_state_dict_pre_hooks](https://github.com/DXist/mmdetection/commit/86cf0999b61daefeec4e5da22b54952d8492452c#diff-c8f3df86003bb97f5edccadac70fb79dR479)
3. mmdet doesn't use native `nn.Module.load_state_dict method` and doesn't support hooks. I've [changed](https://github.com/open-mmlab/mmcv/pull/141) the implementation.
4. At this point I could track compatibility issues loading state dict in strict mode.
5. load_state_dict_pre_hooks are [implemented](https://github.com/DXist/mmdetection/commit/86cf0999b61daefeec4e5da22b54952d8492452c#diff-c8f3df86003bb97f5edccadac70fb79dR555) and I was able to use the snapshot that was done before the changes in this PR.
6. In JIT mode I had to [copy](https://github.com/DXist/mmdetection/commit/86cf0999b61daefeec4e5da22b54952d8492452c#diff-b2c3405ccd893197b1b776c69d0d218bR92) the hooks from nonjitted module instances to `WeakScriptModuleProxy` instances. The latter wrap compiled modules.
After that I was able to use old state dict with JIT-compiled modules.

**Comment by hellock** [comment]
Many thanks! This is indeed an important and large PR, and I will try my best to have it merged soon.

**Comment by DXist** [comment]
@hellock , I've tested against Pytorch 1.3.0, changed the hook restore function to use public API methods.

My current interest is switched to async inference support so I've finished to work on JIT support for now.

**Comment by shuxp** [comment]
Thanks for your excellent job for jit support.

Is there a example of using jit to trace detectors, e.g. TwoStage/SingleStageDetector?

If provided, maybe more people can join to jit support.

**Comment by blankWorld** [comment]
@DXist Hi, I tried to use your method（added jit=True keyword arguments to model['backbone'], model['neck'] and model['rpn_head'] in the detector config and these modules were replaced with ScriptModule instances.）, but failed. Could you provide a complete case. Thanks.

**Comment by DXist** [comment]
@blankWorld do you have error if you jit only `backbone` component? Do you use Pytorch 1.3+?

I've used config similar to https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r50_fpn_1x.py

Currently I'm focused on https://github.com/open-mmlab/mmdetection/pull/1647 since async inference has higher speed up potential than micro optimizations done via JIT compilation to TorchScript.

**Comment by blankWorld** [comment]
@DXist Thank you very much for your reply. I used pytorch1.3.0 and set 'jit=True' in backbone config. 
When i used torch.jit.script the ERROR became:
-------------------------------------
Traceback (most recent call last):
  File "./demo/jit_demo.py", line 51, in <module>
    main()
  File "./demo/jit_demo.py", line 34, in main
    jitted = torch.jit.script(model(return_loss=False,**data))
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1205, in script
    qualified_name = _qualified_name(obj)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/_jit_internal.py", line 635, in _qualified_name
    name = obj.__name__
AttributeError: 'tuple' object has no attribute '__name__'
-------------------------------------
I cloned your uploaded mmdetection-712f32a  to my own github project.
The running script I used is in 'https://github.com/blankWorld/mmdetection-jit/tree/master/712f32a/demo/jit_demo.py'.

**Comment by blankWorld** [comment]
@DXist  Thank you very much for your reply. I used pytorch1.3.0 and set 'jit=True' in backbone config. 
When i used torch.jit.script the ERROR became:
 #----------------------------
Traceback (most recent call last):
  File "./demo/jit_demo.py", line 51, in <module>
    main()
  File "./demo/jit_demo.py", line 34, in main
    jitted = torch.jit.script(model(return_loss=False,**data))
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1205, in script
    qualified_name = _qualified_name(obj)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/_jit_internal.py", line 635, in _qualified_name
    name = obj.__name__
AttributeError: 'tuple' object has no attribute '__name__'
  #----------------------------
I cloned your uploaded mmdetection-712f32a  to my own github project.
The running script I used is in 'https://github.com/blankWorld/mmdetection-jit/tree/master/712f32a/demo/jit_demo.py'.

**Comment by DXist** [comment]
@blankWorld try to script only backbone `nn.Module` instance - not entire model. Use configuration file for the model and set `jit=True` in the backbone config.

**Comment by blankWorld** [comment]
@DXist OK, I script only backbone nn.Module instance and set jit=True in the backbone config.
    with torch.no_grad():
          backbone = build_backbone(config.model.backbone) 
    backbone.eval()
 The above scripts ran successfully, but it failed when I called the "backbone.save('./backbone.pt')" script.
#----------------------------
Traceback (most recent call last):
  File "./demo/jit_demo.py", line 76, in <module>
    main()
  File "./demo/jit_demo.py", line 40, in main
    backbone.save('./backbone.pt')
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1559, in save
    return self._c.save(*args, **kwargs)
RuntimeError: 
Could not export Python function call '_checkpointed_forward'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
at /home/user/jin/jit/mmdetection-712f32a/mmdet/models/backbones/resnet.py:221:18
    def forward(self, x):
        if self.with_cp and x.requires_grad:
            out = self._checkpointed_forward(x)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        else:
            out = self._inner_forward(x)
        out = self.relu(out)
        return out
#----------------------------
I uploaded the script to 'https://github.com/blankWorld/mmdetection-jit/tree/master/712f32a/demo/jit_demo.py'.

**Comment by DXist** [comment]
TorchScript models have own serialization machinery with API methods `torch.jit.save` and `torch.jit.load`. Partially scripted models should use default `model.save / model.load` mechanism.

`_checkpointed_forward` calls functions that can't be statically analyzed/scripted and was excluded from scripting. To use `model.save` you need separate config without enabled `jit` flags.

**Comment by blankWorld** [comment]
Thanks a lot. I have passed the test for the 'ResNet' and 'FPN' modules, but there was an error when I was executing 'RPNHead' module. My configuration is the same as that above and set 'jit=True' in 'rpn_head' config.
#---------------------------------------------
Traceback (most recent call last):
  File "./demo/jit_demo.py", line 85, in <module>
    main()
  File "./demo/jit_demo.py", line 36, in main
    rpn_head = build_head(config.model.rpn_head)
  File "/home/user/jin/jit/mmdetection-712f32a/mmdet/models/builder.py", line 35, in build_head
    return build(cfg, HEADS)
  File "/home/user/jin/jit/mmdetection-712f32a/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/jin/jit/mmdetection-712f32a/mmdet/utils/registry.py", line 91, in build_from_cfg
    jitted = torch.jit.script(orig)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1223, in script
    ast = get_jit_def(obj)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 169, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 198, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 220, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
at /home/user/jin/jit/mmdetection-712f32a/mmdet/core/utils/misc.py:21:30
def multi_apply(func, *args, **kwargs):
                              ~~~~~~~ <--- HERE
    pfunc = partial(func, **kwargs) if kwargs else func
    map_results = map(pfunc, *args)
    return tuple(map(list, zip(*map_results)))
#---------------------------------------------
I uploaded the script to 'https://github.com/blankWorld/mmdetection-jit/tree/master/712f32a/demo/jit_demo.py'.

**Comment by blankWorld** [comment]
@DXist Thanks a million. I have passed the test for the backbone and neck module, but there was an error when i was executing the 'RPNHead' module. My configuration is the same as above, just set 'jit = true' in 'rpn_head' config.
#--------------------------------------------------
Traceback (most recent call last):
  File "./demo/jit_demo.py", line 85, in <module>
    main()
  File "./demo/jit_demo.py", line 36, in main
    rpn_head = build_head(config.model.rpn_head)
  File "/home/user/jin/jit/mmdetection-712f32a/mmdet/models/builder.py", line 35, in build_head
    return build(cfg, HEADS)
  File "/home/user/jin/jit/mmdetection-712f32a/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/jin/jit/mmdetection-712f32a/mmdet/utils/registry.py", line 91, in build_from_cfg
    jitted = torch.jit.script(orig)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1223, in script
    ast = get_jit_def(obj)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 169, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 198, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name)
  File "/home/user/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 220, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
at /home/user/jin/jit/mmdetection-712f32a/mmdet/core/utils/misc.py:21:30
def multi_apply(func, *args, **kwargs):
                              ~~~~~~~ <--- HERE
    pfunc = partial(func, **kwargs) if kwargs else func
    map_results = map(pfunc, *args)
    return tuple(map(list, zip(*map_results)))
#--------------------------------------------------
I uploaded the script to 'https://github.com/blankWorld/mmdetection-jit/tree/master/712f32a/demo/jit_demo.py'.

**Comment by DXist** [comment]
It looks like I committed a fix for this in another PR. Here is a revert of the fix - https://github.com/DXist/mmdetection/commit/da223f618518e475dd8edfdad600c4a55fad5320

**Comment by blankWorld** [comment]
@DXist So far, the "rpn_head", "backbone", "neck" and "bbox_head" modules have been successfully used, but there are still some problems with the "SingleRoIExtractor" and "TwoStageDetector". If the downloaded PR is not correct, could you provide a correct PR ? Thank you very much !

**Comment by DXist** [comment]
@blankWorld I've stopped torch scripting work on rpn_head and decided to look into async inference. All changes I've made are in this PR and in the diff I've mentioned earlier.

**Comment by loveunk** [comment]
@hellock @DXist Thanks for your contributions and is there any plan to update/merge this PR?

**Comment by DXist** [comment]
@loveunk I see there an opportunity to escape the GIL when inference is multithreaded but currently it's not a priority for me.

**Comment by alexattia** [comment]
Any news regarding JIT Support ?

**Comment by ZwwWayne** [comment]
This PR is closed since it is too old to be merged. Will have better design and plan to support torch JIT in the future. New PRs are also welcomed!

**Pull request closed without merging**
