### PR TITLE
add instaboost in coco.py

### PR DESCRIPTION
**Pull request by GothicAi**

### CODE REVIEW

**Comment by whuhangzhang** [comment]
@GothicAi What is the difference between the albu and instaboost? Can instaboost be mixed with other data augmentation methods in detection tasks like coco ? Please give me some advice？

**Comment by Fang-Haoshu** [comment]
@whuhangzhang Hi, instaboost is a data augmentation method introduced in this paper "InstaBoost: Boosting Instance Segmentation via Probability Map Guided Copy-Pasting". It can be used together with other data augmentation methods together.

**Comment by ZwwWayne** [comment]
**Notice**:
1. To reduce the installation burden, by default the code will not install Instaboostfast, the users need to install it manually if they need to use the Instaboost augmentations. The code will raise an error and provide installation instructions if the Instaboost is needed but not installed for convenience.
2. The mmdet team will reimplement all the configs in the codebase when they re-benchmark the codebase after code refactoring. Therefore, only the configs of r50 models are kept to reduce the number of models for re-benchmarking. The results of all the models the authors implemented remain in the `README` and the users can implement the config of big models by themselves based on the r50 configs.
3. For now, the models are maintained by the [authors](https://github.com/GothicAi/Instaboost) in Baidu/Google drives (many thanks), we will provide new models in the future (maybe after re-benchmarking).

**Comment by openmmlab-v** [comment]
Hi @GothicAi ！First of all, we want to express our gratitude for your significant PR in the mmdetection project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
