### PR TITLE
demo

### PR DESCRIPTION
**Pull request by ccjjww**
add lr_config.policy in config setting part

### CODE REVIEW

**Comment by hhaAndroid** [comment]
> add lr_config.policy in config setting part

Can you briefly describe why you want to modify it?

**Comment by ccjjww** [comment]
> > add lr_config.policy in config setting part
> 
> Can you briefly describe why you want to modify it?

> I met AssertionError  in mmcv/runner/baserunner.py at line 351 last night.

**Comment by hhaAndroid** [comment]
> > > add lr_config.policy in config setting part
> > 
> > 
> > Can you briefly describe why you want to modify it?
> 
> I met AssertionError in mmcv/runner/base_runner.py at line 351 last night.

This is because the original config is modified. You might need to rerun the cell that loads the config. please refer to #4603

**Comment by OpenMMLab-Coodinator** [comment]
Hi @ccjjww  ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) , where you can share your experiences, ideas, and build connections with like-minded peers. 

To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
