### PR TITLE
Readme: update py39

### PR DESCRIPTION
**Pull request by breznak**
otherwise openmim pulls in py39, but conda installed torch with py38, so torch packages were not found. With python 3.9 the installation finally works again.

-----------

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix installation process in readme. 

## Modification

openmim now requires python3.9, so bump the version in docs. 

## BC-breaking (Optional)

no

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @breznak 
Thanks for your kind contribution. Would you like to fix the lint issue so that we could merge this PR?
The details can be found by clicking the item of lint check as shown below
image

**Comment by ZwwWayne** [comment]
For now, we still mainly use python 3.8, so this PR will not be merged.

**Comment by breznak** [comment]
@ZwwWayne thanks for reviewing, 
if we stick with python 3.8 as you suggest, then the initial problem is still there: 
> openmim pulls in py39, but conda installed torch with py38, so torch packages were not found.

Steps to reproduce: 
1. setup conda env with python=3.8 as the Readme suggests
2. install openmim (latest?) as readme suggests -> that changes python to 3.9 => torch packages are not found/compatible.

**Comment by OpenMMLab-Assistant005** [comment]
Hi @breznak ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
