### PR TITLE
rename config without change the content

### PR DESCRIPTION
**Pull request by wanghonglie**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

rename config without change the contnet

### CODE REVIEW

**Comment by ZwwWayne** [comment]
autoassign_r50-caffe-fpn_8xb2-1x_coco.py -> autoassign_r50-caffe-fpn_1x_coco.py, 8xb2 can be simplified as a default
faster-rcnn_r50-caffe-fpn_cascade-rpn_1x_coco.py -> cascade-rpn_faster-rcnn_r50-caffe-fpn_1x_coco.py change the configs in the whole directory

**Comment by ZwwWayne** [comment]
- [faster-rcnn_r50-fpn-attention-0010-dcn_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/empirical_attention/faster-rcnn_r50-fpn-attention-0010-dcn_1x_coco.py) -> faster-rcnn_r50-attn0010-dcn-fpn_1x_coco.py

**Comment by ZwwWayne** [comment]
- [mask-rcnn_r50_fpn_carafe_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/carafe/mask-rcnn_r50_fpn_carafe_1x_coco.py) -> mask-rcnn_r50_fpn-carafe_mask-head-carafe_1x_coco.py
- faster-rcnn_r50_fpn_carafe_1x_coco.py -> faster-rcnn_r50_fpn-carafe_1x_coco.py
- [r50-caffe_fpn_cascade-rpn_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/cascade_rpn/r50-caffe_fpn_cascade-rpn_1x_coco.py) -> cascade-rpn_r50-caffe_fpn_1x_coco.py, when used as a RPN, it should be the algorithm name, when used in two-stage detectors, it is a component
- [centernet-update_r50_fpn_amp-lsj-200e_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/centernet/centernet-update_r50_fpn_amp-lsj-200e_coco.py)-> centernet-update_r50_fpn_8xb8-amp-lsj-200e_coco.py, be careful about the batch sizes
- cascade-mask-rcnn_convnext-t-p4-w7_fpn_giou-4conv1f_amp-ms-crop-3x_coco.py -> cascade-mask-rcnn_convnext-t-p4-w7_fpn_4conv1fc-giou_amp-ms-crop-3x_coco.py, we should use 4conv1fc rather than 4conv1f
- [deformable-detr-refine_r50_16xb2-50e_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/deformable_detr/deformable-detr-refine_r50_16xb2-50e_coco.py) -> deformable-detr_refine_r50_16xb2-50e_coco.py, refine is a module, so as the two-stage, we can keep use deformable-detr_refine_two-stage_r50_16xb2-50e_coco.py
- [detectors_cascade-rcnn-r50_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/detectors/detectors_cascade-rcnn-r50_1x_coco.py) -> detectors_cascade-rcnn_r50_1x_coco.py, so as detectors_htc_r50
- [faster-rcnn_r50_fpn_attention-0010_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/empirical_attention/faster-rcnn_r50_fpn_attention-0010_1x_coco.py) -> faster-rcnn_r50-attn0010_fpn_1x_coco.py, also change other configs
- [faster-rcnn-x101_32x8d_fpn_ms-3x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/faster_rcnn/faster-rcnn-x101_32x8d_fpn_ms-3x_coco.py) -> faster-rcnn_x101-32x8d_fpn_ms-3x_coco.py
- [faster-rcnn_r50_fpn_tnr-pretrain_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/faster_rcnn/faster-rcnn_r50_fpn_tnr-pretrain_1x_coco.py) -> faster-rcnn_r50-tnr-pre_fpn_1x_coco.py
- fcos-center-normbbox-centeronreg-giou_r50_fpn_gn-head_8xb8-amp-lsj-200e_coco.py -> fcos_r50_fpn_gn-head-center-normbbox-centeronreg-giou_8xb8-amp-lsj-200e_coco.py
- [fovea-align_r50_fpn_gn-head_4xb4-2x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/foveabox/fovea-align_r50_fpn_gn-head_4xb4-2x_coco.py) -> fovea_r50_fpn_gn-head-align_4xb4-2x_coco.py
- [retinanet_freeanchor_r50_fpn_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/free_anchor/retinanet_freeanchor_r50_fpn_1x_coco.py) -> freeanchor_r50_fpn_1x_coco.py
- [mask-rcnn_r50-fpg_crop640-50e_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/fpg/mask-rcnn_r50-fpg_crop640-50e_coco.py) -> mask-rcnn_r50_pg_crop640-50e_coco.py
- cascade-mask-rcnn_x101-32x4d_fpn_syncbn-backbone-r4-gcb-c3-c5_1x_coco.py -> cascade-mask-rcnn_x101-32x4d-syncbn-r4-gcb-c3-c5_fpn_1x_coco.py
- [cascade-mask-rcnn_hrnetv2p-w32-20e_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/hrnet/cascade-mask-rcnn_hrnetv2p-w32-20e_coco.py) -> cascade-mask-rcnn_hrnetv2p-w32_20e_coco.py
- [maskformer_swin-l-p4-w12_ms-64xb1-300e_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/maskformer/maskformer_swin-l-p4-w12_ms-64xb1-300e_coco.py) -> maskformer_swin-l-p4-w12_64xb1-ms-300e_coco.py
-

**Comment by ZwwWayne** [comment]
- [ssd300_wider-face.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/wider_face/ssd300_wider-face.py) -> ssd300_24e_widerface.py
- [vfnet_res2net-101-mdconv-c3-c5_fpn_ms-2x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/vfnet/vfnet_res2net-101-mdconv-c3-c5_fpn_ms-2x_coco.py) -> vfnet_res2net101-mdconv-c3-c5_fpn_ms-2x_coco.py
- mask-rcnn_r50-caffe_fpn_syncbn-all-rpn-2conv_lsj-400e_coco.py  -> mask-rcnn_r50-caffe_fpn_rpn-2conv_4conv1fc_syncbn-all_lsj-400e_coco.py update the whole dir
- mask-rcnn_r50_fpn_syncbn-all-rpn-2conv_ssj-32xb2-90k_coco.py -> mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_32xb2-ssj-90k_coco.py
- mask-rcnn_r50_fpn_syncbn-all-rpn-2conv_ssj-scp-32xb2-270k_coco.py -> mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_32xb2-ssj-scp-270k_coco.py
- cascade-mask-rcnn_r101_fpn_sample1e-3-seesaw-loss-normed-mask_ms-2x_lvis-v1.py -> cascade-mask-rcnn_r101_fpn_seesaw-loss-normed-mask_sample1e-3-ms-2x_lvis-v1.py, random & sample1e-3 means the data sampling strategy
- [faster-rcnn_r50_fpn_gn-all-scratch_6x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/scratch/faster-rcnn_r50_fpn_gn-all-scratch_6x_coco.py) -> faster-rcnn_r50-scratch_fpn_gn-all_6x_coco.py
-

**Comment by BIGWangYuDong** [comment]
gcnet is a little bit strange 
how about r50-gcb-c3-c5-r16 for example?

**Comment by ZwwWayne** [comment]
[r50-caffe_fpn_cascade-rpn_1x_coco.py](https://github.com/wanghonglie/mmdetection/blob/rename_config2/configs/cascade_rpn/r50-caffe_fpn_cascade-rpn_1x_coco.py) -> cascade-rpn_r50-caffe_fpn_1x_coco.py

**Comment by chhluo** [comment]
yolov3_mobilenetv2_320_300e_coco, yolov3_mobilenetv2_mstrain-416_300e_coco `batch_size = 8 x b24`

How about adding epoch in `yolact`, `ssd` config file name?

batch_size for strong_baseline is not 8 * 2, consider to add it in config file name

**Pull request merged**
