### PR TITLE
Korabelnikov patch 4

### PR DESCRIPTION
**Pull request by korabelnikov**
sorry but 2 minor topics in one PR
first one allows custom probability in Expand transfrom (0 can disable it without making pipeline broken)
second one fix size groups in metric evaluation

### CODE REVIEW

**Comment by hellock** [comment]
Thanks for the PR! You may check the status of your branch which seems inconsistent with current upstream. Custom probability in Expand (#1633) and printing area ranges (#1614) have already been merged.

**Comment by korabelnikov** [comment]
rebased. take a look, please

**Comment by hellock** [comment]
We follow the PASCAL VOC and ImageNet DET evaluation metric in `eval_map`, so that `+1` is needed. You may refer to the official matlab code in the devkit of those datasets.

**Comment by korabelnikov** [comment]
Sad to hear that Pascal VOC and ImageNet Det have such error (or their own tricky logic)

**Pull request closed without merging**
