### PR TITLE
fixing crash caused by `get_root_logger`

### PR DESCRIPTION
**Pull request by qingswu**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

hot fix a crash caused by `get_root_logger` when cfg.log_level is not None, cause first arg in `get_root_logger` is `log_file`, not `log_level`

## Modification

using keyword to call `get_root_logger` to pass the correct arg to `log_level`

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @qingswu , thanks for you fix. Would you like to check other place that may also have similar issues?

**Review by hhaAndroid — APPROVED** [review]

**Comment by qingswu** [comment]
> 
> 
> Hi @qingswu , thanks for you fix. Would you like to check other place that may also have similar issues?

no in this repo, but same bug in different mmlab projects, which I guess caused by copy/paste, lol

**Comment by ZwwWayne** [comment]
> > 
> 
> > 
> 
> > Hi @qingswu , thanks for you fix. Would you like to check other place that may also have similar issues?
> 
> 
> 
> no in this repo, but same bug in different mmlab projects, which I guess caused by copy/paste, lol

Thanks, I will notify them.

**Comment by OpenMMLab-Coodinator** [comment]
Hi @qingswu  ！First of all, we want to express our gratitude for your significant PR in this project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
