### PR TITLE
[Docs] Fix Faster R-CNN Readme

### PR DESCRIPTION
**Pull request by sudoAimer**
## Motivation

The Link in Faster R-CNN ReadMe is wrong.

## Modification

Fix the link of faster_rcnn_r50_fpn_1x_coco.py to faster_rcnn_r50_fpn_giou_1x_coco.py

### CODE REVIEW

**Comment by RangiLyu** [comment]
Thanks for your contribution! Please sign the CLA first.
image

**Comment by RangiLyu** [comment]
And the lint failed, Please run `pip install pre-commit` and then run `pre-commit run --all-files` to fix the lint.

**Review by RangiLyu — APPROVED** [review]

**Comment by ZwwWayne** [comment]
Hi @sudoAimer ,
Thanks for your kind PR. It seems that there are conflicts between your PR and the targeted branch. Could you solve the conflicts so that we could eventually merge this PR?

You can find more details in the place shown as below:
image

**Review by ZwwWayne — APPROVED** [review]

**Comment by OpenMMLab-Miao** [comment]
Hi @sudoAimer ！First of all, we want to express our gratitude for your significant PR in the MMDet project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
