### PR TITLE
Add fix on the bbox loss_weight of the PAA head

### PR DESCRIPTION
**Pull request by gkagkos**
## Motivation

I was having a look on the PAA head and I accidentally saw that the loss weight used on the bbox, belongs on the cls. Which I think is wrong. 

## Modification

I changed [this](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/paa_head.py#L247-L252) to use the weight of cls.

### CODE REVIEW

**Comment by hhaAndroid** [comment]
@gkagkos Thank you very much for your feedback, it seems to be a bug indeed. Can you fix it based on dev 2.19.1? We plan to merge to dev 2.19.1?

**Review by hhaAndroid — COMMENTED** [review]
LGTM

**Comment by gkagkos** [comment]
Will do shortly.

**Comment by gkagkos** [comment]
@hhaAndroid sorry for being late. Changed master tod dev 2.19.1

**Comment by ZwwWayne** [comment]
Hi @gkagkos ,
Thanks for your kind contribution. We plan to merge this PR in dev-v2.19.1. Would you like to sign CLA so that we can merge this PR?

**Comment by gkagkos** [comment]
Done

**Comment by gkagkos** [comment]
@ZwwWayne can you please close the PR ?

**Comment by hhaAndroid** [comment]
> 

Please sync the code.

**Review by hhaAndroid — APPROVED** [review]

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
