### PR TITLE
Fix the config link of the fp16 on retinanet

### PR DESCRIPTION
**Pull request by kimnamu**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
Config and some train scripts did not work properly on fp16/retinanet

## Modification
Modify one of the configuration links on the retinet is invalid. The other links were correct.
Additionally, other train script was modified in the same issue.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist
1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by RangiLyu — DISMISSED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Comment by ZwwWayne** [comment]
Need to resolve conflicts before merge.

**Review by hhaAndroid — APPROVED** [review]

**Comment by kimnamu** [comment]
@ZwwWayne
I'm not sure I have the authority can resolve merge conflict.
Now you can resolve merge conflict apply `income commit`.

**Comment by ZwwWayne** [comment]
Can be merged after resolving conlicts.

**Review by hhaAndroid — APPROVED** [review]

**Comment by RangiLyu** [comment]
resolve #6927

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
