### PR TITLE
[Enhance] Make scipy as a default dependency in runtime

### PR DESCRIPTION
**Pull request by BIGWangYuDong**
Since DETR series become very popular, bipart matching becomes a default.
Therefore, it would be better to make scipy a default runtime dependency rather than optional

Resolve PR: https://github.com/open-mmlab/mmdetection/issues/8962

### CODE REVIEW

**Review by Czm369 — DISMISSED** [review]
LGTM

**Comment by ZwwWayne** [comment]
should also clean these try excee in the code

**Comment by BIGWangYuDong** [comment]
Done

**Review by RangiLyu — APPROVED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
