### PR TITLE
update

### PR DESCRIPTION
**Pull request by cm-nakamura-shogo**
## Motivation

Build jupyter environment under docker environment and support docker-compose.
We think it is useful to have a notebook environment for more extensive tutorials.

## Modification

- Fix GPG key in dockerfile
- Install jupyterlab and mim in dockerfile
- Create new docker-compose.yml file

### CODE REVIEW

**Comment by ZwwWayne** [comment]
image
Hi @cm-nakamura-shogo ,
The CLA failed. Could you sing the CLA so that we can merge this PR?

**Comment by cm-nakamura-shogo** [comment]
image
@ZwwWayne 
I have two notifications from the CLA Assistant on me, one I was able to sign, but the second one stayed "not signed yet" even after processing.
This may be an effect of accidentally closing and reopening the PR once.
What should I do?

**Comment by ZwwWayne** [comment]
Hi @cm-nakamura-shogo ,
Thanks for your kind PR. However, it is unlikely that we will merge this PR because the modification is irrelevant and may not be common to more general usages.

**Comment by cm-nakamura-shogo** [comment]
Thank you very much. I have confirmed that it was taken in by another PR ([#7951](https://github.com/open-mmlab/mmdetection/issues/7951)).

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @cm-nakamura-shogo ！We are grateful for your efforts in helping improve mmdetection open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
