### PR TITLE
Fix size mismatch in multiclass_nms

### PR DESCRIPTION
**Pull request by shinya7y**

### CODE REVIEW

**Comment by jshilong** [comment]
Thanks for your contribution, but in https://github.com/open-mmlab/mmdetection/pull/4912 we would refactor all post-processes and fix it in that PR.

**Comment by shinya7y** [comment]
Thank you for your heavy work for refactoring.
Please close this PR after fix in that PR.

**Comment by jshilong** [comment]
Because #4912  is temporarily blocked, I think this PR can be merged first. @ZwwWayne

**Review by jshilong — APPROVED** [review]
LGTM.

**Review by hhaAndroid — APPROVED** [review]

**Pull request merged**
