### PR TITLE
fix: correct hrnet forward func

### PR DESCRIPTION
**Pull request by royxue**
According to the original hrnet implementation
according to https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/lib/models/pose_hrnet.py#L257

### CODE REVIEW

**Comment by xvjiarui** [comment]
Hi @royxue 
In the original implementation, `j` index starts from `1`, while ours starts from `0`. So it should be the same.

**Comment by royxue** [comment]
@xvjiarui  Hi, Jerry
For result, it should be the same;
The reason why it's better to keep the same as original implementation is, when convert this HRNet to Caffe, current implementation will causing key missing error;
I think it might cause by this y initial value

**Comment by ZwwWayne** [comment]
Since the implementation is the same, this PR will not be merged. The key missing error should be caused by other reasons. If it is confirmed that changing the y initial value is necessary. Feel free to reopen this PR and add a unit test to make sure the implementations in this PR is the same as the original one.

**Comment by OpenMMLab-Assistant-007** [comment]
Hi
@royxue 
We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
