### PR TITLE
Implementing YOLOv3 architecture

### PR DESCRIPTION
**Pull request by wuhy08**
Hi MMlab,

I am Haoyu Wu, an employee at Western Digital. I have implemented the YOLOv3 architecture in the mmdetection framework. Hope that is helpful to community. It is noted that the contribution comes from my work at Western Digital, therefore each files have a header of copyright claims. But we agree to use Apache 2.0 license.

I have pretrained weight file. I wonder what is the best way to share that.

Thank you!

### CODE REVIEW

**Comment by niaoyu** [comment]
> Hi MMlab,
> 
> I am Haoyu Wu, an employee at Western Digital. I have implemented the YOLOv3 architecture in the mmdetection framework. Hope that is helpful to community. It is noted that the contribution comes from my work at Western Digital, therefore each files have a header of copyright claims. But we agree to use Apache 2.0 license.
> 
> I have pretrained weight file. I wonder what is the best way to share that.
> 
> Thank you!

amazing pr!
How about the map compare with the original one ?

**Comment by CRmost** [comment]
> 
> 
> Hi MMlab,
> 
> I am Haoyu Wu, an employee at Western Digital. I have implemented the YOLOv3 architecture in the mmdetection framework. Hope that is helpful to community. It is noted that the contribution comes from my work at Western Digital, therefore each files have a header of copyright claims. But we agree to use Apache 2.0 license.
> 
> I have pretrained weight file. I wonder what is the best way to share that.
> 
> Thank you!

Where is the pretrained weight file??

**Comment by liugl7** [comment]
please give the download link to **"darknet_state_dict_only.pth"**

**Comment by liugl7** [comment]
> Hi MMlab,
> 
> I am Haoyu Wu, an employee at Western Digital. I have implemented the YOLOv3 architecture in the mmdetection framework. Hope that is helpful to community. It is noted that the contribution comes from my work at Western Digital, therefore each files have a header of copyright claims. But we agree to use Apache 2.0 license.
> 
> I have pretrained weight file. I wonder what is the best way to share that.
> 
> Thank you!

please give the download link to "darknet_state_dict_only.pth"
thank you very much !

**Comment by EletronicElephant** [comment]
@wuhy08 Hello, great thanks to your contribution. Would you please offer a download link to the pretrained model?

**Comment by EletronicElephant** [comment]
@CRmost  @liugl7 
You can try
```
https://drive.google.com/file/d/1-59qCzvSOCvVFCQ9HDggHA8xUQFR4LDx/view?usp=sharing
```
, which is extracted from the author's another repo

**Comment by xvjiarui** [comment]
Hi @wuhy08 
Thanks for your contribution and sorry for the delay. 
Could you please clean up the comment in the config files?

**Comment by wuhy08** [comment]
Hi @xvjiarui 

I cleaned the comments in the config file. The __init__ files have some conflicts. I wonder how to deal with that.

**Comment by xvjiarui** [comment]
Hi @wuhy08 
You could try `git merge open-mmlab master` to solve conflicts from your side.

**Comment by xvjiarui** [comment]
@wuhy08 
Also, it would be nice if I could have the link to your pre-trained weight and trained model so that I could work on reproducing. 
`READMD.md` is suggested to included under the `configs/yolo`, where you could also provide your links and results.

**Comment by xvjiarui** [comment]
Hi @wuhy08 
FYI, `ConvModule` is just refactored in https://github.com/open-mmlab/mmdetection/pull/2239, which could be used to replace `ConvLayer` in your implementation.

**Comment by wuhy08** [comment]
@xvjiarui 

I will try to merge your current master to my branch, resolve any conflict, and test it. It might take a few ways. I will let you know by then.

**Comment by GreenTeaHua** [comment]
everything is ok？

**Comment by wuhy08** [comment]
Hi @xvjiarui 

Sorry for the delay due to coronavirus. But I pushed more commits to get it streamlined. I haven't use your new `ConvModule` since it require substantial amount of work including retraining/state_dict converting. So I will leave it for other contributors. I also uploaded my training checkpoint to Google Drive, linked in README. I hope that can be stored in your centralized storage in case it is unintentionally deleted. I am not authorized to merge so I think some conflicts have to be resolved by authorized merger.

Thank you and stay healthy!

**Comment by miaoshuyu** [comment]
@wuhy08 
hi, I run your code and miss this problem, do you know why. 
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function.

**Comment by hasanirtiza** [comment]
@miaoshuyu 
If you have not solved it already, at line 132 of `mmdet/apis/train.py`, when he is calling 
 `model = MMDistributedDataParallel(model.cuda(), device_ids=[torch.cuda.current_device()],
        broadcast_buffers=False]) `

add an additional argument `find_unused_parameters=True`.

 `model = MMDistributedDataParallel(model.cuda(), device_ids=[torch.cuda.current_device()],
        broadcast_buffers=False, find_unused_parameters=True) `

**Comment by ZwwWayne** [comment]
Since YOLOv3 is supported by https://github.com/open-mmlab/mmdetection/pull/3083. This PR is closed. Thanks for your contribution.

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @wuhy08 ！We are grateful for your efforts in helping improve mmdetection open-source project during your personal time. 

Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）

Thank you again for your contribution❤

**Pull request closed without merging**
