### PR TITLE
Fixing build-errors on Windows

### PR DESCRIPTION
**Pull request by wswday**
`-D__CUDA_NO_HALF_OPERATORS__`
`-D__CUDA_NO_HALF_CONVERSIONS__`
`-D__CUDA_NO_HALF2_OPERATORS__`
These compile args are default on Linux, but need explicit setting on windows.

This PR will not affect build on Linux.

### CODE REVIEW

**Comment by hellock** [comment]
Thanks for the fix! The master branch has been updated and you can just modify one `setup.py` file now. Could you pull the latest commits and format your code according to the expected [code style](https://github.com/open-mmlab/mmdetection/blob/master/CONTRIBUTING.md#code-style)?

**Comment by wswday** [comment]
Merged.

**Comment by hellock** [comment]
Hi @wswday, I made some minor modifications on the code style. Could you help test the compilation on windows? I will merge it if everything goes well.

**Comment by wswday** [comment]
1.Adding 'cxx' key for extra_compile_args
  Because it will be check

2.Adding type-cast to long for first parameter of THCCeilDiv
  Parameters of  THCCeilDiv are long type.  facebookresearch/maskrcnn-benchmark#409

3.Ignoring resource setting on windows
  There is no resource pack on windows

**Comment by hellock** [comment]
Looks good!
BTW, the specified args are used by default in the master branch of PyTorch (but not in version 1.1), thus we can omit them in the future release.

**Comment by trungpham2606** [comment]
@wswday Hello, thank you for your fixing on Windows build. But I am still not able to compile modules on my PC.
image

**Pull request merged**
