### PR TITLE
Fix coco loader empty images

### PR DESCRIPTION
**Pull request by mmeendez8**
This PR is related with https://github.com/open-mmlab/mmdetection/issues/3023 I followed @Shallowte idea and added a regression test. So when `filter_empty_gt` is `False` all images will be loaded independently of their annotations.
I am not sure if this is the best approach (it might be more efficient to filter images [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L40) instead ), just let me know how this could be improved

### CODE REVIEW

**Comment by mmeendez8** [comment]
I cannot really understand why tests are failing with:
`AttributeError: 'CocoDataset' object has no attribute 'img_ids'`
It should be fullfilled in after calling `load_annotations` (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L40)

Am I missing something? This is working fine locally

**Comment by ZwwWayne** [comment]
Hi @mmeendez8 ,
Thanks for your kind contribution.
Are you using the newest `cocoapi` and the same environment as those in CI? I do not find any bug after reading the code yet. It is weird, but we cannot merge this PR if it cannot pass CI.

**Comment by mmeendez8** [comment]
Hi @ZwwWayne ,
I have installed a fresh version of mmdet following installation instructions and everything works fine. I think there must be something wrong with Continuous Integration. I review the code and run locally multiple times but can't figure out what's going on.

**Comment by ZwwWayne** [comment]
This PR is closed because it is continued with more refactoring in  #3695.

**Pull request closed without merging**
