### PR TITLE
Update focal_loss.py to consist with the original formula.

### PR DESCRIPTION
**Pull request by yarkable**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Enhance the code to make it more easily comprehensible. As in the paper, pt denotes the probability, and the coefficient of Focal Loss is ``\alpha * (1 - pt) ** \gamma``

## Modification

Modified the computation method of the Focal Loss coefficient.

### CODE REVIEW

**Review by ryylcc — COMMENTED** [review]
Thanks for the suggestion.  This code has been widely used for a long time, so we don't advise to modify it due to mathematical transformation. You could pull request to add comments to explain it.

**Comment by yarkable** [comment]
OK, now I add some comments and leave the code unchanged. @ryylcc

**Comment by hhaAndroid** [comment]
@yarkable Please fix the lint

**Comment by yarkable** [comment]
@hhaAndroid done!

**Review by ryylcc — APPROVED** [review]

**Review by hhaAndroid — APPROVED** [review]

**Pull request merged**
