### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lmk123568**
hi 这是给mmdet增加了数据下载脚本，用户可以直接点击脚本运行，自动解压，免去了手动下载的烦扰，方便新手入门学习，我考虑了如何在win运行，考虑python脚本，但是不如bash脚本灵活，如果可以参考我的代码，我将乐意提供coco等其他数据下载脚本并维护

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @lmk123568 ,
Thanks for your PR. This is really beneficial to the repo. Would you like to also update related docs before merge?

**Comment by lmk123568** [comment]
> Hi @lmk123568 ,
> Thanks for your PR. This is really beneficial to the repo. Would you like to also update related docs before merge?

感谢回复，你的意思是写一篇md文档，说明如何使用新加入的自动脚本吗

**Comment by ZwwWayne** [comment]
> > Hi @lmk123568 ,
> > Thanks for your PR. This is really beneficial to the repo. Would you like to also update related docs before merge?
> 
> 感谢回复，你的意思是写一篇md文档，说明如何使用新加入的自动脚本吗

Yes. Or at least lead users to the script so that users could know and use this script more easily.

**Comment by lmk123568** [comment]
> > > Hi @lmk123568 ,
> > > Thanks for your PR. This is really beneficial to the repo. Would you like to also update related docs before merge?
> > 
> > 
> > 感谢回复，你的意思是写一篇md文档，说明如何使用新加入的自动脚本吗
> 
> Yes. Or at least lead users to the script so that users could know and use this script more easily.

okey，just do it today

**Comment by hhaAndroid** [comment]
Is there any progress?

**Comment by OpenMMLab-Coodinator** [comment]
Hi @lmk123568 ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) , where you can share your experiences, ideas, and build connections with like-minded peers. 

To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
