### PR TITLE
[feature]增加cpu可以支持的运行 add a **cpu version** of training-api

### PR DESCRIPTION
**Pull request by EasonQYS**
if device == 'cuda':
            model = MMDataParallel(model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
        elif device == 'cpu':
            model = model.cpu()
        else:
            raise ValueError(F'unsupported device name {device}.')

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

在mmcls的api中可以使用cpu训练，但mmdet不行。就是因为少了这几行代码，故再此处添加。

## Modification

在train_detector函数添加传参device，并且加入判断，看是否是cpu。从而决定模型在何处训练。
这样，默认device为cuda，原有的工程不会受影响，而增加了对cpu训练的支持。

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by shinya7y** [comment]
https://github.com/open-mmlab/mmdetection/pull/7016 supports CPU training.
The PR has already been merged into the `dev` branch.

**Comment by EasonQYS** [comment]
though #7016 has support cpu training, the style is different from the https://github.com/open-mmlab/mmclassification/tree/dev/mmcls/apis/train.py , so I recommand to use the same style like "add a perameter device", and I think it is easier to understand for api users.
Besides, I recommand to uniform all mmlab api code to the same style to support cpu training.

**Comment by hhaAndroid** [comment]
@EasonQYS Maybe we can discuss which way of writing is the best and choose the best.

**Comment by EasonQYS** [comment]
[question] As for #7016  , if I want to use mmdet/apis/train.py , how to understand "device_ids=cfg.gpu_ids"?
What should be equel to cfg.gpu_ids?
As I know, cfg.gpu_ids should be a non-negtive sequence like [0,] or [0,1,]. but not accept [-1,] or -1.

**Comment by AronLin** [comment]
Can you train a model with your modification? If you do not use the `MMDataParallel`, how can you deal with the data wrapped in the `DataContainer`?

**Comment by EasonQYS** [comment]
> Can you train a model with your modification? If you do not use the `MMDataParallel`, how can you deal with the data wrapped in the `DataContainer`?

Thank you to remind me, and I have fix if by check mmcv.__version__. 
In older version, I think we don't need to put data to parallel for cpu training.

**Comment by AronLin** [comment]
> > Can you train a model with your modification? If you do not use the `MMDataParallel`, how can you deal with the data wrapped in the `DataContainer`?
> 
> Thank you to remind me, and I have fix if by check mmcv.**version**. In older version, I think we don't need to put data to parallel for cpu training.

Have you tried the training progress with CPU? With the below line, MMDet can not deal with the `DataContainer`, we must use MMDP to deal with the data wrapped in the `DataContainer` or there will be an error!

    model = model.cpu()

Moreover, MMCls will modify the code according to our current version, so this PR is suggested to be closed.

**Comment by ZwwWayne** [comment]
Thanks @EasonQYS  for your kind contribution. However, model.cpu() is not applicable to make mmdet models run on CPU, it still need MMDP to deal with datacontainer. Therefore, this PR will be closed.

**Pull request closed without merging**
