### PR TITLE
[Fix] Fix img_shape.

### PR DESCRIPTION
**Pull request by RangiLyu**
img_shape should be (h, w)

TODO:

- [x] Unit tests

### CODE REVIEW

**Comment by hhaAndroid** [comment]
LGTM

**Review by BIGWangYuDong — APPROVED** [review]
LGTM

**Comment by hhaAndroid** [comment]
@RangiLyu CI Failed

**Comment by RangiLyu** [comment]
> @RangiLyu CI Failed

TestInferenceBenchmark failed

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
