### PR TITLE
Fix typo in mmdet.datasets.pipelines.formating

### PR DESCRIPTION
**Pull request by nijkah**
## Motivation

"formating" in mmdet.datasets.pipelines is not an appropriate word.
**formatting** is correct.

## Modification

So I changed its name and added a deprecated warning as in [mmseg](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/formating.py)

### CODE REVIEW

**Comment by RangiLyu** [comment]
Hi, please change the import  in `mmdet/datasets/pipelines/__init__.py`

**Comment by nijkah** [comment]
@RangiLyu  I updated it. Thank you.

**Review by ZwwWayne — APPROVED** [review]

**Comment by nijkah** [comment]
Is there any reason that checks was cancelled?
Something I have to update?
I already checked lint.

**Review by RangiLyu — APPROVED** [review]
I re-runed the CI and the lint passed. Can be merged now.

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
