### PR TITLE
Add batch inference

### PR DESCRIPTION
**Pull request by yhcao6**

### CODE REVIEW

**Comment by chicm** [comment]
Does it support GroupSampler?  If not, does it mean we should group the images before inference to avoid that a 400x800 image and a 800x400 image are put in a same batch?

**Comment by gittigxuy** [comment]
@yhcao6 ,so how could  I use this code to multi batch inference?

**Comment by yhcao6** [comment]
> @yhcao6 ,so how could I use this code to multi batch inference?

Which model?

**Comment by gittigxuy** [comment]
faster rcnn

**Comment by yhcao6** [comment]
> faster rcnn

For example if you want to test with 2 images per GPU, then you need to add `imgs_per_gpu_override=2,` after this line. Currently you must obtain the rule that len(test_dataset) % (#GPU x #imgs_per_gpu) == 0
https://github.com/open-mmlab/mmdetection/blob/5b9c5dd45fc5446a1c2f6c1fce571ad504e4d9ce/configs/faster_rcnn_r50_fpn_1x.py#L139

**Comment by gittigxuy** [comment]
Thanks,Furthermore,how about the data augment function,How could I use data-pipeline brench.From now on,it just support ssd,mask rcnn.htc,if I want to support faster rcnn,how could I fix the code?

**Comment by gittigxuy** [comment]
@yhcao6 ,how about multi-batch test in the guide anchor faster rcnn,I fix the code reference by your diff code,but it still error.I think I should fix the guide anchor model file,but how could I fix it?

**Comment by gittigxuy** [comment]
@yhcao6,I think you should Add the code in the models/detectors/test_mixins.py RPNTestMixin class simple_test_rpn function to support multi-batch inference

**Comment by mosheliv** [comment]
will this work for retinanet models?

**Comment by yhcao6** [comment]
Currently this work supports retinanet.

**Comment by ievbu** [comment]
Is this PR compatible with HTC models? If yes, then how could I use it for batch inference?

**Comment by greathope** [comment]
support mask-rcnn?

**Comment by greathope** [comment]
It seems your pr is far behind current branch， can you transfer your code to current branch？

**Comment by greathope** [comment]
I find this pr doesn't accelerate the inference, on the contrary, setting bs to 5, the inference takes more time  than bs 1

**Comment by zvadaszi** [comment]
Is batch inference support for Cascade R-CNN in plans?

**Comment by bruceyang2012** [comment]
Can you add batch inference in the latest version of mmdet？Thank you.

**Pull request closed without merging**
