### PR TITLE
modify mmdet/models/detectors/base.py and mmdet/models/detectors/casc…

### PR DESCRIPTION
**Pull request by mangdian**
Fix two bugs:

Change https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L213 to mask = segms[i].
Change https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/cascade_rcnn.py#L34 to return xxxx

### CODE REVIEW

**Comment by yhcao6** [comment]
Thanks for fixing the bug.
There is also a similar bug when enabling `show` flag in single_gpu_test, for example:
`python tools/test.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py models/mask_rcnn/mask_rcnn_r50_fpn_1x_coco/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth --show`
Could you also fix it?

**Comment by hellock** [comment]
@mangdian Could you sign the CLA to make this PR merged?

**Comment by hellock** [comment]
Fixed in #2824.

**Comment by OpenMMLab-Assistant003** [comment]
Hi @Tord-Zhang！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @Tord-Zhang

**Pull request closed without merging**
